cd /workfs2/cms/huahuil/4topCode/CMSSW_10_6_27/src/FourTop/objectSelection/Jobsubmit_seperate/ttG/

hep_sub ttG_outTree_6.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttG/log/outTree_6.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttG/log/outTree_6.err
hep_sub ttG_outTree_1.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttG/log/outTree_1.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttG/log/outTree_1.err
hep_sub ttG_outTree_3.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttG/log/outTree_3.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttG/log/outTree_3.err
hep_sub ttG_outTree_2.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttG/log/outTree_2.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttG/log/outTree_2.err
hep_sub ttG_outTree_0.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttG/log/outTree_0.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttG/log/outTree_0.err
hep_sub ttG_outTree_5.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttG/log/outTree_5.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttG/log/outTree_5.err
hep_sub ttG_outTree_4.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttG/log/outTree_4.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttG/log/outTree_4.err
