cd /workfs2/cms/huahuil/4topCode/CMSSW_10_6_27/src/FourTop/objectSelection/Jobsubmit_seperate/ttH_nonbb/

hep_sub ttH_nonbb_outTree_11.sh -mem 5000 -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttH_nonbb/log/outTree_11.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttH_nonbb/log/outTree_11.err
hep_sub ttH_nonbb_outTree_6.sh -mem 5000 -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttH_nonbb/log/outTree_6.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttH_nonbb/log/outTree_6.err
hep_sub ttH_nonbb_outTree_21.sh -mem 5000 -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttH_nonbb/log/outTree_21.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttH_nonbb/log/outTree_21.err
hep_sub ttH_nonbb_outTree_18.sh -mem 5000 -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttH_nonbb/log/outTree_18.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttH_nonbb/log/outTree_18.err
hep_sub ttH_nonbb_outTree_1.sh -mem 5000 -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttH_nonbb/log/outTree_1.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttH_nonbb/log/outTree_1.err
hep_sub ttH_nonbb_outTree_15.sh -mem 5000 -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttH_nonbb/log/outTree_15.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttH_nonbb/log/outTree_15.err
hep_sub ttH_nonbb_outTree_16.sh -mem 5000 -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttH_nonbb/log/outTree_16.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttH_nonbb/log/outTree_16.err
hep_sub ttH_nonbb_outTree_3.sh -mem 5000 -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttH_nonbb/log/outTree_3.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttH_nonbb/log/outTree_3.err
hep_sub ttH_nonbb_outTree_7.sh -mem 5000 -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttH_nonbb/log/outTree_7.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttH_nonbb/log/outTree_7.err
hep_sub ttH_nonbb_outTree_2.sh -mem 5000 -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttH_nonbb/log/outTree_2.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttH_nonbb/log/outTree_2.err
hep_sub ttH_nonbb_outTree_0.sh -mem 5000 -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttH_nonbb/log/outTree_0.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttH_nonbb/log/outTree_0.err
hep_sub ttH_nonbb_outTree_12.sh -mem 5000 -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttH_nonbb/log/outTree_12.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttH_nonbb/log/outTree_12.err
hep_sub ttH_nonbb_outTree_19.sh -mem 5000 -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttH_nonbb/log/outTree_19.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttH_nonbb/log/outTree_19.err
hep_sub ttH_nonbb_outTree_9.sh -mem 5000 -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttH_nonbb/log/outTree_9.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttH_nonbb/log/outTree_9.err
hep_sub ttH_nonbb_outTree_10.sh -mem 5000 -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttH_nonbb/log/outTree_10.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttH_nonbb/log/outTree_10.err
hep_sub ttH_nonbb_outTree_17.sh -mem 5000 -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttH_nonbb/log/outTree_17.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttH_nonbb/log/outTree_17.err
hep_sub ttH_nonbb_outTree_14.sh -mem 5000 -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttH_nonbb/log/outTree_14.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttH_nonbb/log/outTree_14.err
hep_sub ttH_nonbb_outTree_20.sh -mem 5000 -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttH_nonbb/log/outTree_20.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttH_nonbb/log/outTree_20.err
hep_sub ttH_nonbb_outTree_8.sh -mem 5000 -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttH_nonbb/log/outTree_8.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttH_nonbb/log/outTree_8.err
hep_sub ttH_nonbb_outTree_13.sh -mem 5000 -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttH_nonbb/log/outTree_13.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttH_nonbb/log/outTree_13.err
hep_sub ttH_nonbb_outTree_5.sh -mem 5000 -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttH_nonbb/log/outTree_5.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttH_nonbb/log/outTree_5.err
hep_sub ttH_nonbb_outTree_4.sh -mem 5000 -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttH_nonbb/log/outTree_4.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/ttH_nonbb/log/outTree_4.err
