cd /workfs2/cms/huahuil/4topCode/CMSSW_10_6_27/src/FourTop/objectSelection/Jobsubmit_seperate/ww/

hep_sub outTree_11.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_11.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_11.err
hep_sub outTree_35.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_35.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_35.err
hep_sub outTree_6.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_6.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_6.err
hep_sub outTree_21.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_21.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_21.err
hep_sub outTree_29.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_29.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_29.err
hep_sub outTree_15.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_15.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_15.err
hep_sub outTree_36.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_36.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_36.err
hep_sub outTree_16.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_16.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_16.err
hep_sub outTree_33.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_33.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_33.err
hep_sub outTree_7.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_7.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_7.err
hep_sub outTree_2.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_2.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_2.err
hep_sub outTree_0.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_0.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_0.err
hep_sub outTree_32.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_32.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_32.err
hep_sub outTree_12.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_12.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_12.err
hep_sub outTree_19.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_19.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_19.err
hep_sub outTree_9.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_9.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_9.err
hep_sub outTree_10.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_10.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_10.err
hep_sub outTree_17.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_17.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_17.err
hep_sub outTree_14.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_14.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_14.err
hep_sub outTree_27.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_27.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_27.err
hep_sub outTree_20.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_20.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_20.err
hep_sub outTree_8.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_8.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_8.err
hep_sub outTree_13.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_13.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_13.err
hep_sub outTree_31.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_31.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_31.err
hep_sub outTree_37.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_37.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_37.err
hep_sub outTree_30.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_30.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_30.err
hep_sub outTree_5.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_5.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_5.err
hep_sub outTree_4.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_4.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/2016postVFP/v0_testing/ww/log/outTree_4.err
