cd /workfs2/cms/huahuil/4topCode/CMSSW_10_6_27/src/FourTop/objectSelection/Jobsubmit_seperate/wz/

hep_sub wz_outTree_11.sh -mem 5000 -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/wz/log/outTree_11.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/wz/log/outTree_11.err
hep_sub wz_outTree_1.sh -mem 5000 -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/wz/log/outTree_1.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/wz/log/outTree_1.err
hep_sub wz_outTree_15.sh -mem 5000 -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/wz/log/outTree_15.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/wz/log/outTree_15.err
hep_sub wz_outTree_7.sh -mem 5000 -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/wz/log/outTree_7.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/wz/log/outTree_7.err
hep_sub wz_outTree_0.sh -mem 5000 -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/wz/log/outTree_0.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/wz/log/outTree_0.err
hep_sub wz_outTree_12.sh -mem 5000 -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/wz/log/outTree_12.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/wz/log/outTree_12.err
hep_sub wz_outTree_9.sh -mem 5000 -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/wz/log/outTree_9.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/wz/log/outTree_9.err
hep_sub wz_outTree_14.sh -mem 5000 -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/wz/log/outTree_14.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/wz/log/outTree_14.err
hep_sub wz_outTree_8.sh -mem 5000 -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/wz/log/outTree_8.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/wz/log/outTree_8.err
hep_sub wz_outTree_4.sh -mem 5000 -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/wz/log/outTree_4.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_postVFP/v3_onlyMETandPreselectionNoHLT/wz/log/outTree_4.err
