cd /workfs2/cms/huahuil/4topCode/CMSSW_10_6_27/src/FourTop/objectSelection/jobs_seperata/dy_fxfx_1j/

hep_sub dy_fxfx_1j_outTree_42.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_preVFP/v6_noHLTSelection_addedMulitjetForSingleMu/mc/dy_fxfx_1j/log/outTree_42.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_preVFP/v6_noHLTSelection_addedMulitjetForSingleMu/mc/dy_fxfx_1j/log/outTree_42.err
hep_sub dy_fxfx_1j_outTree_23.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_preVFP/v6_noHLTSelection_addedMulitjetForSingleMu/mc/dy_fxfx_1j/log/outTree_23.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_preVFP/v6_noHLTSelection_addedMulitjetForSingleMu/mc/dy_fxfx_1j/log/outTree_23.err
hep_sub dy_fxfx_1j_outTree_6.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_preVFP/v6_noHLTSelection_addedMulitjetForSingleMu/mc/dy_fxfx_1j/log/outTree_6.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_preVFP/v6_noHLTSelection_addedMulitjetForSingleMu/mc/dy_fxfx_1j/log/outTree_6.err
hep_sub dy_fxfx_1j_outTree_3.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_preVFP/v6_noHLTSelection_addedMulitjetForSingleMu/mc/dy_fxfx_1j/log/outTree_3.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_preVFP/v6_noHLTSelection_addedMulitjetForSingleMu/mc/dy_fxfx_1j/log/outTree_3.err
hep_sub dy_fxfx_1j_outTree_7.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_preVFP/v6_noHLTSelection_addedMulitjetForSingleMu/mc/dy_fxfx_1j/log/outTree_7.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_preVFP/v6_noHLTSelection_addedMulitjetForSingleMu/mc/dy_fxfx_1j/log/outTree_7.err
hep_sub dy_fxfx_1j_outTree_0.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_preVFP/v6_noHLTSelection_addedMulitjetForSingleMu/mc/dy_fxfx_1j/log/outTree_0.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_preVFP/v6_noHLTSelection_addedMulitjetForSingleMu/mc/dy_fxfx_1j/log/outTree_0.err
hep_sub dy_fxfx_1j_outTree_64.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_preVFP/v6_noHLTSelection_addedMulitjetForSingleMu/mc/dy_fxfx_1j/log/outTree_64.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_preVFP/v6_noHLTSelection_addedMulitjetForSingleMu/mc/dy_fxfx_1j/log/outTree_64.err
hep_sub dy_fxfx_1j_outTree_22.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_preVFP/v6_noHLTSelection_addedMulitjetForSingleMu/mc/dy_fxfx_1j/log/outTree_22.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_preVFP/v6_noHLTSelection_addedMulitjetForSingleMu/mc/dy_fxfx_1j/log/outTree_22.err
hep_sub dy_fxfx_1j_outTree_67.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_preVFP/v6_noHLTSelection_addedMulitjetForSingleMu/mc/dy_fxfx_1j/log/outTree_67.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_preVFP/v6_noHLTSelection_addedMulitjetForSingleMu/mc/dy_fxfx_1j/log/outTree_67.err
hep_sub dy_fxfx_1j_outTree_9.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_preVFP/v6_noHLTSelection_addedMulitjetForSingleMu/mc/dy_fxfx_1j/log/outTree_9.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_preVFP/v6_noHLTSelection_addedMulitjetForSingleMu/mc/dy_fxfx_1j/log/outTree_9.err
hep_sub dy_fxfx_1j_outTree_10.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_preVFP/v6_noHLTSelection_addedMulitjetForSingleMu/mc/dy_fxfx_1j/log/outTree_10.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_preVFP/v6_noHLTSelection_addedMulitjetForSingleMu/mc/dy_fxfx_1j/log/outTree_10.err
hep_sub dy_fxfx_1j_outTree_41.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_preVFP/v6_noHLTSelection_addedMulitjetForSingleMu/mc/dy_fxfx_1j/log/outTree_41.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_preVFP/v6_noHLTSelection_addedMulitjetForSingleMu/mc/dy_fxfx_1j/log/outTree_41.err
hep_sub dy_fxfx_1j_outTree_8.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_preVFP/v6_noHLTSelection_addedMulitjetForSingleMu/mc/dy_fxfx_1j/log/outTree_8.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_preVFP/v6_noHLTSelection_addedMulitjetForSingleMu/mc/dy_fxfx_1j/log/outTree_8.err
hep_sub dy_fxfx_1j_outTree_65.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_preVFP/v6_noHLTSelection_addedMulitjetForSingleMu/mc/dy_fxfx_1j/log/outTree_65.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_preVFP/v6_noHLTSelection_addedMulitjetForSingleMu/mc/dy_fxfx_1j/log/outTree_65.err
hep_sub dy_fxfx_1j_outTree_66.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_preVFP/v6_noHLTSelection_addedMulitjetForSingleMu/mc/dy_fxfx_1j/log/outTree_66.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_preVFP/v6_noHLTSelection_addedMulitjetForSingleMu/mc/dy_fxfx_1j/log/outTree_66.err
hep_sub dy_fxfx_1j_outTree_5.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_preVFP/v6_noHLTSelection_addedMulitjetForSingleMu/mc/dy_fxfx_1j/log/outTree_5.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_preVFP/v6_noHLTSelection_addedMulitjetForSingleMu/mc/dy_fxfx_1j/log/outTree_5.err
hep_sub dy_fxfx_1j_outTree_4.sh -o /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_preVFP/v6_noHLTSelection_addedMulitjetForSingleMu/mc/dy_fxfx_1j/log/outTree_4.log -e /publicfs/cms/user/huahuil/tauOfTTTT_NanoAOD/UL2016_preVFP/v6_noHLTSelection_addedMulitjetForSingleMu/mc/dy_fxfx_1j/log/outTree_4.err
