cd /publicfs/cms/user/fabioiemmi/CMSSW_10_6_27/src/FourTop/objectSelection/jobs_seperata/st_schan_leptonDecay/

hep_sub st_schan_leptonDecay_outTree_11.sh -o /publicfs/cms/user/fabioiemmi/TauOfTTTT_NanoAOD/UL2016_preVFP/v8_METfiltersAndPresel_fixJSONmask/mc/st_schan_leptonDecay/log/outTree_11.log -e /publicfs/cms/user/fabioiemmi/TauOfTTTT_NanoAOD/UL2016_preVFP/v8_METfiltersAndPresel_fixJSONmask/mc/st_schan_leptonDecay/log/outTree_11.err
hep_sub st_schan_leptonDecay_outTree_6.sh -o /publicfs/cms/user/fabioiemmi/TauOfTTTT_NanoAOD/UL2016_preVFP/v8_METfiltersAndPresel_fixJSONmask/mc/st_schan_leptonDecay/log/outTree_6.log -e /publicfs/cms/user/fabioiemmi/TauOfTTTT_NanoAOD/UL2016_preVFP/v8_METfiltersAndPresel_fixJSONmask/mc/st_schan_leptonDecay/log/outTree_6.err
hep_sub st_schan_leptonDecay_outTree_1.sh -o /publicfs/cms/user/fabioiemmi/TauOfTTTT_NanoAOD/UL2016_preVFP/v8_METfiltersAndPresel_fixJSONmask/mc/st_schan_leptonDecay/log/outTree_1.log -e /publicfs/cms/user/fabioiemmi/TauOfTTTT_NanoAOD/UL2016_preVFP/v8_METfiltersAndPresel_fixJSONmask/mc/st_schan_leptonDecay/log/outTree_1.err
hep_sub st_schan_leptonDecay_outTree_3.sh -o /publicfs/cms/user/fabioiemmi/TauOfTTTT_NanoAOD/UL2016_preVFP/v8_METfiltersAndPresel_fixJSONmask/mc/st_schan_leptonDecay/log/outTree_3.log -e /publicfs/cms/user/fabioiemmi/TauOfTTTT_NanoAOD/UL2016_preVFP/v8_METfiltersAndPresel_fixJSONmask/mc/st_schan_leptonDecay/log/outTree_3.err
hep_sub st_schan_leptonDecay_outTree_7.sh -o /publicfs/cms/user/fabioiemmi/TauOfTTTT_NanoAOD/UL2016_preVFP/v8_METfiltersAndPresel_fixJSONmask/mc/st_schan_leptonDecay/log/outTree_7.log -e /publicfs/cms/user/fabioiemmi/TauOfTTTT_NanoAOD/UL2016_preVFP/v8_METfiltersAndPresel_fixJSONmask/mc/st_schan_leptonDecay/log/outTree_7.err
hep_sub st_schan_leptonDecay_outTree_2.sh -o /publicfs/cms/user/fabioiemmi/TauOfTTTT_NanoAOD/UL2016_preVFP/v8_METfiltersAndPresel_fixJSONmask/mc/st_schan_leptonDecay/log/outTree_2.log -e /publicfs/cms/user/fabioiemmi/TauOfTTTT_NanoAOD/UL2016_preVFP/v8_METfiltersAndPresel_fixJSONmask/mc/st_schan_leptonDecay/log/outTree_2.err
hep_sub st_schan_leptonDecay_outTree_0.sh -o /publicfs/cms/user/fabioiemmi/TauOfTTTT_NanoAOD/UL2016_preVFP/v8_METfiltersAndPresel_fixJSONmask/mc/st_schan_leptonDecay/log/outTree_0.log -e /publicfs/cms/user/fabioiemmi/TauOfTTTT_NanoAOD/UL2016_preVFP/v8_METfiltersAndPresel_fixJSONmask/mc/st_schan_leptonDecay/log/outTree_0.err
hep_sub st_schan_leptonDecay_outTree_9.sh -o /publicfs/cms/user/fabioiemmi/TauOfTTTT_NanoAOD/UL2016_preVFP/v8_METfiltersAndPresel_fixJSONmask/mc/st_schan_leptonDecay/log/outTree_9.log -e /publicfs/cms/user/fabioiemmi/TauOfTTTT_NanoAOD/UL2016_preVFP/v8_METfiltersAndPresel_fixJSONmask/mc/st_schan_leptonDecay/log/outTree_9.err
hep_sub st_schan_leptonDecay_outTree_10.sh -o /publicfs/cms/user/fabioiemmi/TauOfTTTT_NanoAOD/UL2016_preVFP/v8_METfiltersAndPresel_fixJSONmask/mc/st_schan_leptonDecay/log/outTree_10.log -e /publicfs/cms/user/fabioiemmi/TauOfTTTT_NanoAOD/UL2016_preVFP/v8_METfiltersAndPresel_fixJSONmask/mc/st_schan_leptonDecay/log/outTree_10.err
hep_sub st_schan_leptonDecay_outTree_8.sh -o /publicfs/cms/user/fabioiemmi/TauOfTTTT_NanoAOD/UL2016_preVFP/v8_METfiltersAndPresel_fixJSONmask/mc/st_schan_leptonDecay/log/outTree_8.log -e /publicfs/cms/user/fabioiemmi/TauOfTTTT_NanoAOD/UL2016_preVFP/v8_METfiltersAndPresel_fixJSONmask/mc/st_schan_leptonDecay/log/outTree_8.err
hep_sub st_schan_leptonDecay_outTree_5.sh -o /publicfs/cms/user/fabioiemmi/TauOfTTTT_NanoAOD/UL2016_preVFP/v8_METfiltersAndPresel_fixJSONmask/mc/st_schan_leptonDecay/log/outTree_5.log -e /publicfs/cms/user/fabioiemmi/TauOfTTTT_NanoAOD/UL2016_preVFP/v8_METfiltersAndPresel_fixJSONmask/mc/st_schan_leptonDecay/log/outTree_5.err
hep_sub st_schan_leptonDecay_outTree_4.sh -o /publicfs/cms/user/fabioiemmi/TauOfTTTT_NanoAOD/UL2016_preVFP/v8_METfiltersAndPresel_fixJSONmask/mc/st_schan_leptonDecay/log/outTree_4.log -e /publicfs/cms/user/fabioiemmi/TauOfTTTT_NanoAOD/UL2016_preVFP/v8_METfiltersAndPresel_fixJSONmask/mc/st_schan_leptonDecay/log/outTree_4.err
