// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in /workfs2/cms/huahuil/4topCode/CMSSW_10_2_20_UL/src/FourTop/hua/writeVariableHist/./writeHist_forBtagRCal.h;
#pragma link C++ defined_in "/workfs2/cms/huahuil/4topCode/CMSSW_10_2_20_UL/src/FourTop/hua/writeVariableHist/./writeHist_forBtagRCal.C";

#endif
