//////////////////////////////////////////////////////////
// This class has been automatically generated on
// Sun Feb  7 10:53:21 2021 by ROOT version 6.20/06
// from TChain TNT/BOOM/
//////////////////////////////////////////////////////////

#ifndef objectTSelector_h
#define objectTSelector_h

#include <TROOT.h>
#include <TChain.h>
#include <TFile.h>
#include <TSelector.h>
#include <TTreeReader.h>
#include <TTreeReaderValue.h>
#include <TTreeReaderArray.h>

// Headers needed by this particular selector
#include <vector>
#include "TLorentzVector.h"
#include "TH1D.h"



class objectTSelector : public TSelector {
public :
   TTreeReader     fReader;  //!the tree reader
   TTree          *fChain = 0;   //!pointer to the analyzed TTree or TChain

   Bool_t isdata = false;
   // Bool_t isdata = true;
    Bool_t MetFilters = true;
    // Bool_t MetFilters = false;
    Bool_t HLTSelection = true;
    // Bool_t HLTSelection = false;
    // Bool_t preselection = true;
    // Bool_t preselection = false;
    Bool_t preselection = true;
//

   Long64_t   fProcessed = 0;
   Long64_t eventsPassed = 0;
   Long64_t tausT_total = 0;
   Long64_t tausL_total = 0;
   Long64_t tausF_total = 0;
   Long64_t elesT_total =0;
   Long64_t elesL_total =0;
   Long64_t elesF_total =0;
    Long64_t mounsT_total = 0;
    Long64_t mounsF_total = 0;
    Long64_t mounsL_total = 0;

    Long64_t jets_total = 0;
    Long64_t bjetsM_total =0;
    
    TFile *outputfile;
    TTree *tree;
    TTree *allEvents;
    TH1D  *h_genWeight ;

    //
    Double_t genWeight_allEvents;


Int_t    Flag_goodVertices_ ;
Int_t    Flag_globalSuperTightHalo2016Filter_ ;
Int_t    Flag_HBHENoiseFilter_ ;
Int_t    Flag_HBHENoiseIsoFilter_ ;
Int_t    Flag_EcalDeadCellTriggerPrimitiveFilter_ ;
Int_t    Flag_BadPFMuonFilter_ ;
Int_t    Flag_eeBadScFilter_ ;
    //HLT
    Int_t HLT_PFHT450_SixJet40_BTagCSV_p056_ ;
    Int_t HLT_PFHT400_SixJet30_DoubleBTagCSV_p056_ ;
    Int_t HLT_DoubleMediumIsoPFTau35_Trk1_eta2p1_Reg_ ;
    Int_t HLT_DoubleMediumCombinedIsoPFTau35_Trk1_eta2p1_Reg_ ;
    Int_t HLT_DoubleMediumChargedIsoPFTau35_Trk1_eta2p1_Reg_ ;
    Int_t HLT_DoubleTightChargedIsoPFTau35_Trk1_TightID_eta2p1_Reg_ ;
    Int_t HLT_DoubleMediumChargedIsoPFTau40_Trk1_TightID_eta2p1_Reg_ ;
    Int_t HLT_DoubleTightChargedIsoPFTau40_Trk1_eta2p1_Reg_ ;
    Int_t HLT_DoubleMediumChargedIsoPFTauHPS35_Trk1_eta2p1_Reg_ ;//this Int_t HLT doesn't exist in ntuple
 
    Int_t HLT_Ele27_eta2p1_WPTight_Gsf_ ;
    Int_t HLT_Ele27_eta2p1_WPLoose_Gsf_ ;
    Int_t HLT_Ele27_WPTight_Gsf_ ;
    Int_t HLT_IsoMu22_ ;
    Int_t HLT_Ele25_eta2p1_WPTight_Gsf_ ;
    Int_t HLT_IsoTkMu22_ ;
    Int_t HLT_IsoMu24_ ;
    Int_t HLT_IsoTkMu24_ ;
    Int_t HLT_IsoMu22_eta2p1_ ;
    Int_t HLT_IsoTkMu22_eta2p1_ ;
    Int_t HLT_Mu50_ ;
    Int_t HLT_TkMu50_ ;
    Int_t HLT_Ele32_WPTight_Gsf_ ;
    Int_t HLT_Ele35_WPTight_Gsf_ ;
    Int_t HLT_IsoMu27_ ;

    Int_t HLT_Ele24_eta2p1_WPLoose_Gsf_LooseIsoPFTau20_ ;
    Int_t HLT_Ele24_eta2p1_WPLoose_Gsf_LooseIsoPFTau20_SingleL1_ ;
    Int_t HLT_Ele24_eta2p1_WPLoose_Gsf_LooseIsoPFTau30_ ;
    Int_t HLT_Ele24_eta2p1_WPTight_Gsf_LooseChargedIsoPFTau30_eta2p1_CrossL1_ ;
    Int_t HLT_Ele24_eta2p1_WPTight_Gsf_LooseChargedIsoPFTauHPS30_eta2p1_CrossL1_ ;
    Int_t HLT_IsoMu19_eta2p1_LooseIsoPFTau20_SingleL1_ ;
    Int_t HLT_IsoMu20_eta2p1_LooseChargedIsoPFTau27_eta2p1_CrossL1_ ;
    Int_t HLT_IsoMu20_eta2p1_LooseChargedIsoPFTauHPS27_eta2p1_CrossL1_ ;

    Int_t HLT_DoubleEle24_22_eta2p1_WPLoose_Gsf_ ;
    Int_t HLT_DoubleEle33_CaloIdL_MW_ ;
    Int_t HLT_DoubleEle33_CaloIdL_GsfTrkIdVL_MW_ ;
    Int_t HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_ ;
    Int_t HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_ ;
    Int_t HLT_DoubleMu33NoFiltersNoVtx_ ;
    Int_t HLT_DoubleMu23NoFiltersNoVtxDisplaced_ ;
    Int_t HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_ ;
    Int_t HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_Mass3p8_ ;
    Int_t HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_ ;
    Int_t HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ_ ;
    Int_t HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_ ;
    Int_t HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ_ ;
    Int_t HLT_Mu23_TrkIsoVVL_Ele8_CaloIdL_TrackIdL_IsoVL_ ;
    Int_t HLT_Mu23_TrkIsoVVL_Ele8_CaloIdL_TrackIdL_IsoVL_DZ_ ;
    Int_t HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_ ;
    Int_t HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_ ;
    Int_t HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_ ;
    Int_t HLT_Mu12_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ_ ;

    Int_t HLT_Ele16_Ele12_Ele8_CaloIdL_TrackIdL_ ;
    Int_t HLT_Mu8_DiEle12_CaloIdL_TrackIdL_ ;
    Int_t HLT_DiMu9_Ele9_CaloIdL_TrackIdL_DZ_ ;
    Int_t HLT_TripleMu_12_10_5_ ;
    Int_t HLT_DiMu9_Ele9_CaloIdL_TrackIdL_ ;


    vector<TLorentzVector> muonsL; vector<Int_t> muonsL_index;
    vector<TLorentzVector> muonsF; vector<Int_t> muonsF_index;
    vector<TLorentzVector> muonsT; vector<Int_t> muonsT_index;
    vector<TLorentzVector> eleMVAL; vector<Int_t> eleMVAL_index;
    vector<TLorentzVector> eleMVAF; vector<Int_t> eleMVAF_index;
    vector<TLorentzVector> eleMVAT; vector<Int_t> eleMVAT_index;
    // vector<TLorentzVector> eleMVAL_IsoT; vector<Int_t> eleMVAL_IsoT_index;
    // vector<TLorentzVector> eleMVAF_IsoT; vector<Int_t> eleMVAF_IsoT_index;
    // vector<TLorentzVector> eleMVAT_IsoT; vector<Int_t> eleMVAT_IsoT_index;
    vector<TLorentzVector> leptonsMVAF; 
    vector<TLorentzVector> leptonsMVAT; 
    vector<TLorentzVector> leptonsMVAL; 
    vector<TLorentzVector> tausL; vector<Int_t> tausL_index;
    vector<TLorentzVector> tausF; vector<Int_t> tausF_index;
    vector<TLorentzVector> tausT; vector<Int_t> tausT_index;
    vector<TLorentzVector> jets; vector<Int_t> jets_index; vector<Double_t> jets_btags; 
    vector<TLorentzVector> bjetsL; vector<Int_t> bjetsL_index; vector<Double_t> bjetsL_btags;
    vector<TLorentzVector> bjetsM; vector<Int_t> bjetsM_index; vector<Double_t> bjetsM_btags;
    vector<TLorentzVector> bjetsT; vector<Int_t> bjetsT_index; vector<Double_t> bjetsT_btags;
    vector<TLorentzVector> forwardJets; vector<Int_t> forwardJets_index; vector<Double_t> forwardJets_btags;
    vector<TLorentzVector>  nonbjetsL;
    vector<TLorentzVector>  nonbjetsM;
    vector<TLorentzVector>  nonbjetsT;
    // vector<TLorentzVector> ; vector<Int_t> ;
    // vector<TLorentzVector> ; vector<Int_t> ;
    // vector<TLorentzVector> ; vector<Int_t> ;
    // vector<TLorentzVector> ; vector<Int_t> ;
    vector<Double_t> patElectron_charge_;
    // vector<Double_t> patElectron_charge_;
    vector<Double_t> Tau_charge_;
    vector<Double_t> Muon_charge_;
    Double_t Met_pt;
    Double_t Met_phi;
    vector<TLorentzVector> tops_toptagger;

    vector<TLorentzVector> genTaus; 
    vector<TLorentzVector> genEles;
    vector<TLorentzVector> genMuons;

    //weight
    Double_t EVENT_prefireWeight_;
    Double_t PUWeight_;
    Double_t EVENT_genWeight_;

    //functions I added
     void SelectMuons(vector<TLorentzVector> &SelectedMuons, vector<Int_t> &SelectedMuonsIndex, const Int_t type);
     void SelectTaus(vector<TLorentzVector> &SelectedTaus, vector<Int_t> &SelectedTausIndex,const Int_t TauWP, const vector<TLorentzVector> LeptonsMVAL);
     void SelectTops(vector<TLorentzVector> &SelectedTops);
     void SelectJets(const Int_t jetType,const  bool deepJet, vector<TLorentzVector> &SelectedJets, vector<Double_t> &SelectedJetsBTags, vector<Int_t>  &SelectedJetsIndex , const Int_t SysJes, const Int_t SysJer, const vector<TLorentzVector> LeptonsMVAF, const vector<TLorentzVector> SelectedTausL );
     void MetCorrection(Int_t SysJes, Int_t SysJer, Double_t &MET);
     void selectGenTaus( vector<TLorentzVector> &genTaus );
     void selectGenEles( vector<TLorentzVector> &genEles );
     void selectGenMuons( vector<TLorentzVector> &genMuons );
     void SelectElectronsMVA(vector<TLorentzVector> &SelectedElectrons, vector<Int_t> &SelectedElectronsIndex,const Int_t type);

     void makeBranch( TTree*  tree, Bool_t isdata);
   // Readers to access the data (delete the ones you do not need).
   // if  ( !isdata ){
   // ???why if not working here?
    // all the branches only in MC
   // Double_t *EVENT_genWeight;
     // TTreeReaderValue<Double_t> EVENT_genWeight = {fReader, "EVENT_event"};
   
       TTreeReaderArray<double> Gen_pt = {fReader, "Gen_pt"};
       TTreeReaderArray<double> Gen_eta = {fReader, "Gen_eta"};
       TTreeReaderArray<double> Gen_phi = {fReader, "Gen_phi"};
       TTreeReaderArray<double> Gen_energy = {fReader, "Gen_energy"};
       TTreeReaderArray<double> Gen_charge = {fReader, "Gen_charge"};
       // TTreeReaderArray<double> Gen_vx = {fReader, "Gen_vx"};
       // TTreeReaderArray<double> Gen_vy = {fReader, "Gen_vy"};
       // TTreeReaderArray<double> Gen_vz = {fReader, "Gen_vz"};
       // TTreeReaderArray<double> Gen_status = {fReader, "Gen_status"};
       TTreeReaderArray<double> Gen_pdg_id = {fReader, "Gen_pdg_id"};
       TTreeReaderArray<double> Gen_motherpdg_id = {fReader, "Gen_motherpdg_id"};
       // TTreeReaderArray<double> Gen_numDaught = {fReader, "Gen_numDaught"};
       // TTreeReaderArray<double> Gen_numMother = {fReader, "Gen_numMother"};
       // TTreeReaderArray<int> Gen_BmotherIndex = {fReader, "Gen_BmotherIndex"};
       // TTreeReaderArray<int> Gen_BmotherIndices = {fReader, "Gen_BmotherIndices"};
       // TTreeReaderArray<int> Gen_BdaughtIndices = {fReader, "Gen_BdaughtIndices"};
       // TTreeReaderArray<int> Gen_isPromptFinalState = {fReader, "Gen_isPromptFinalState"};
       // TTreeReaderArray<int> Gen_isDirectPromptTauDecayProductFinalState = {fReader, "Gen_isDirectPromptTauDecayProductFinalState"};
   TTreeReaderArray<double> Muon_gen_pt = {fReader, "Muon_gen_pt"};
   TTreeReaderArray<double> Muon_gen_eta = {fReader, "Muon_gen_eta"};
   TTreeReaderArray<double> Muon_gen_phi = {fReader, "Muon_gen_phi"};
   TTreeReaderArray<double> Muon_gen_en = {fReader, "Muon_gen_en"};
   TTreeReaderArray<int> Muon_gen_pdgId = {fReader, "Muon_gen_pdgId"};
   TTreeReaderArray<int> Muon_gen_isPromptFinalState = {fReader, "Muon_gen_isPromptFinalState"};
   TTreeReaderArray<int> Muon_gen_isDirectPromptTauDecayProductFinalState = {fReader, "Muon_gen_isDirectPromptTauDecayProductFinalState"};
   
   // Double_t EVENT_genWeight;
   TTreeReaderValue<Double_t> EVENT_genWeight = {fReader, "EVENT_genWeight"};


   TTreeReaderArray<double> patElectron_gen_pt = {fReader, "patElectron_gen_pt"};
   TTreeReaderArray<double> patElectron_gen_eta = {fReader, "patElectron_gen_eta"};
   TTreeReaderArray<double> patElectron_gen_phi = {fReader, "patElectron_gen_phi"};
   TTreeReaderArray<double> patElectron_gen_en = {fReader, "patElectron_gen_en"};
   TTreeReaderArray<int> patElectron_gen_pdgId = {fReader, "patElectron_gen_pdgId"};
   TTreeReaderArray<double> Jet_gen_pt = {fReader, "Jet_gen_pt"};
   TTreeReaderArray<double> Jet_gen_eta = {fReader, "Jet_gen_eta"};
   TTreeReaderArray<double> Jet_gen_phi = {fReader, "Jet_gen_phi"};
   TTreeReaderArray<double> Jet_gen_en = {fReader, "Jet_gen_en"};
   TTreeReaderArray<double> Jet_partonFlavour = {fReader, "Jet_partonFlavour"};
   TTreeReaderArray<double> Jet_hadronFlavour = {fReader, "Jet_hadronFlavour"};
   // };
   
   //
   //
   //
   //
   //
   //
   // TTreeReaderValue<Int_t> HiggsDecay = {fReader, "HiggsDecay"};
   TTreeReaderValue<ULong64_t> EVENT_event = {fReader, "EVENT_event"};
   TTreeReaderValue<Int_t> EVENT_run = {fReader, "EVENT_run"};
   TTreeReaderValue<Int_t> EVENT_lumiBlock = {fReader, "EVENT_lumiBlock"};

   // TTreeReaderArray<double> EVENT_genWeights = {fReader, "EVENT_genWeights"};
   TTreeReaderArray<double> EVENT_psWeights = {fReader, "EVENT_psWeights"};
   TTreeReaderArray<double> EVENT_rWeights = {fReader, "EVENT_rWeights"};
   // TTreeReaderValue<Double_t> EVENT_genHT = {fReader, "EVENT_genHT"};
   // TTreeReaderValue<Double_t> EVENT_genPt = {fReader, "EVENT_genPt"};
   TTreeReaderValue<Double_t> EVENT_rhopog = {fReader, "EVENT_rhopog"};
   TTreeReaderValue<Double_t> EVENT_rhotth = {fReader, "EVENT_rhotth"};
   TTreeReaderValue<Double_t> EVENT_originalXWGTUP = {fReader, "EVENT_originalXWGTUP"};
   TTreeReaderValue<Double_t> EVENT_rWeightSUM = {fReader, "EVENT_rWeightSUM"};
   TTreeReaderValue<Double_t> EVENT_scalePDF = {fReader, "EVENT_scalePDF"};
   TTreeReaderValue<Double_t> EVENT_Q2tthbbWeightUp = {fReader, "EVENT_Q2tthbbWeightUp"};
   TTreeReaderValue<Double_t> EVENT_Q2tthbbWeightDown = {fReader, "EVENT_Q2tthbbWeightDown"};
   TTreeReaderValue<Double_t> EVENT_PDFv1WeightUp = {fReader, "EVENT_PDFv1WeightUp"};
   TTreeReaderValue<Double_t> EVENT_PDFv1WeightDown = {fReader, "EVENT_PDFv1WeightDown"};
   TTreeReaderValue<Double_t> EVENT_PDFv1WeightCentral = {fReader, "EVENT_PDFv1WeightCentral"};
   TTreeReaderValue<Double_t> EVENT_PDFv1WeightMean = {fReader, "EVENT_PDFv1WeightMean"};
   TTreeReaderValue<Double_t> EVENT_PDFv1WeightStdDev = {fReader, "EVENT_PDFv1WeightStdDev"};
   TTreeReaderValue<Int_t> EVENT_PDFv1_lhaid = {fReader, "EVENT_PDFv1_lhaid"};
   TTreeReaderValue<Double_t> EVENT_PDFv2WeightUp = {fReader, "EVENT_PDFv2WeightUp"};
   TTreeReaderValue<Double_t> EVENT_PDFv2WeightDown = {fReader, "EVENT_PDFv2WeightDown"};
   TTreeReaderValue<Double_t> EVENT_PDFv2WeightCentral = {fReader, "EVENT_PDFv2WeightCentral"};
   TTreeReaderValue<Double_t> EVENT_PDFv2WeightMean = {fReader, "EVENT_PDFv2WeightMean"};
   TTreeReaderValue<Double_t> EVENT_PDFv2WeightStdDev = {fReader, "EVENT_PDFv2WeightStdDev"};
   TTreeReaderValue<Int_t> EVENT_PDFv2_lhaid = {fReader, "EVENT_PDFv2_lhaid"};
   TTreeReaderValue<Double_t> EVENT_PDFv3WeightUp = {fReader, "EVENT_PDFv3WeightUp"};
   TTreeReaderValue<Double_t> EVENT_PDFv3WeightDown = {fReader, "EVENT_PDFv3WeightDown"};
   TTreeReaderValue<Double_t> EVENT_PDFv3WeightCentral = {fReader, "EVENT_PDFv3WeightCentral"};
   TTreeReaderValue<Double_t> EVENT_PDFv3WeightMean = {fReader, "EVENT_PDFv3WeightMean"};
   TTreeReaderValue<Double_t> EVENT_PDFv3WeightStdDev = {fReader, "EVENT_PDFv3WeightStdDev"};
   TTreeReaderValue<Int_t> EVENT_PDFv3_lhaid = {fReader, "EVENT_PDFv3_lhaid"};
   TTreeReaderValue<Double_t> EVENT_PDFv4WeightUp = {fReader, "EVENT_PDFv4WeightUp"};
   TTreeReaderValue<Double_t> EVENT_PDFv4WeightDown = {fReader, "EVENT_PDFv4WeightDown"};
   TTreeReaderValue<Double_t> EVENT_PDFv4WeightCentral = {fReader, "EVENT_PDFv4WeightCentral"};
   TTreeReaderValue<Double_t> EVENT_PDFv4WeightMean = {fReader, "EVENT_PDFv4WeightMean"};
   TTreeReaderValue<Double_t> EVENT_PDFv4WeightStdDev = {fReader, "EVENT_PDFv4WeightStdDev"};
   TTreeReaderValue<Int_t> EVENT_PDFv4_lhaid = {fReader, "EVENT_PDFv4_lhaid"};
   TTreeReaderValue<Double_t> EVENT_PDFv5WeightUp = {fReader, "EVENT_PDFv5WeightUp"};
   TTreeReaderValue<Double_t> EVENT_PDFv5WeightDown = {fReader, "EVENT_PDFv5WeightDown"};
   TTreeReaderValue<Double_t> EVENT_PDFv5WeightCentral = {fReader, "EVENT_PDFv5WeightCentral"};
   TTreeReaderValue<Double_t> EVENT_PDFv5WeightMean = {fReader, "EVENT_PDFv5WeightMean"};
   TTreeReaderValue<Double_t> EVENT_PDFv5WeightStdDev = {fReader, "EVENT_PDFv5WeightStdDev"};
   TTreeReaderValue<Int_t> EVENT_PDFv5_lhaid = {fReader, "EVENT_PDFv5_lhaid"};
   TTreeReaderValue<Double_t> EVENT_PDFv6WeightUp = {fReader, "EVENT_PDFv6WeightUp"};
   TTreeReaderValue<Double_t> EVENT_PDFv6WeightDown = {fReader, "EVENT_PDFv6WeightDown"};
   TTreeReaderValue<Double_t> EVENT_PDFv6WeightCentral = {fReader, "EVENT_PDFv6WeightCentral"};
   TTreeReaderValue<Double_t> EVENT_PDFv6WeightMean = {fReader, "EVENT_PDFv6WeightMean"};
   TTreeReaderValue<Double_t> EVENT_PDFv6WeightStdDev = {fReader, "EVENT_PDFv6WeightStdDev"};
   TTreeReaderValue<Int_t> EVENT_PDFv6_lhaid = {fReader, "EVENT_PDFv6_lhaid"};
   TTreeReaderValue<Double_t> EVENT_fixedGridRhoFastjetCentral = {fReader, "EVENT_fixedGridRhoFastjetCentral"};
   TTreeReaderValue<Double_t> EVENT_fixedGridRhoFastjetCentralChargedPileUp = {fReader, "EVENT_fixedGridRhoFastjetCentralChargedPileUp"};
   TTreeReaderValue<Double_t> EVENT_fixedGridRhoFastjetCentralNeutral = {fReader, "EVENT_fixedGridRhoFastjetCentralNeutral"};
   TTreeReaderValue<Double_t> EVENT_prefireWeight = {fReader, "EVENT_prefireWeight"};
   TTreeReaderValue<Double_t> EVENT_prefireWeightUp = {fReader, "EVENT_prefireWeightUp"};
   TTreeReaderValue<Double_t> EVENT_prefireWeightDown = {fReader, "EVENT_prefireWeightDown"};
   TTreeReaderValue<Int_t> n_lhe_higgs = {fReader, "n_lhe_higgs"};
   TTreeReaderArray<double> lhe_higgs_pt = {fReader, "lhe_higgs_pt"};
   TTreeReaderArray<double> lhe_higgs_eta = {fReader, "lhe_higgs_eta"};
   TTreeReaderArray<double> lhe_higgs_phi = {fReader, "lhe_higgs_phi"};
   TTreeReaderArray<double> lhe_higgs_energy = {fReader, "lhe_higgs_energy"};
   TTreeReaderValue<Int_t> Flag_HBHENoiseFilter = {fReader, "Flag_HBHENoiseFilter"};
   TTreeReaderValue<Int_t> Flag_HBHENoiseIsoFilter = {fReader, "Flag_HBHENoiseIsoFilter"};
   TTreeReaderValue<Int_t> Flag_CSCTightHaloFilter = {fReader, "Flag_CSCTightHaloFilter"};
   TTreeReaderValue<Int_t> Flag_CSCTightHaloTrkMuUnvetoFilter = {fReader, "Flag_CSCTightHaloTrkMuUnvetoFilter"};
   TTreeReaderValue<Int_t> Flag_CSCTightHalo2015Filter = {fReader, "Flag_CSCTightHalo2015Filter"};
   TTreeReaderValue<Int_t> Flag_HcalStripHaloFilter = {fReader, "Flag_HcalStripHaloFilter"};
   TTreeReaderValue<Int_t> Flag_hcalLaserEventFilter = {fReader, "Flag_hcalLaserEventFilter"};
   TTreeReaderValue<Int_t> Flag_EcalDeadCellTriggerPrimitiveFilter = {fReader, "Flag_EcalDeadCellTriggerPrimitiveFilter"};
   TTreeReaderValue<Int_t> Flag_EcalDeadCellBoundaryEnergyFilter = {fReader, "Flag_EcalDeadCellBoundaryEnergyFilter"};
   TTreeReaderValue<Int_t> Flag_goodVertices = {fReader, "Flag_goodVertices"};
   TTreeReaderValue<Int_t> Flag_eeBadScFilter = {fReader, "Flag_eeBadScFilter"};
   TTreeReaderValue<Int_t> Flag_ecalLaserCorrFilter = {fReader, "Flag_ecalLaserCorrFilter"};
   TTreeReaderValue<Int_t> Flag_trkPOGFilters = {fReader, "Flag_trkPOGFilters"};
   TTreeReaderValue<Int_t> Flag_chargedHadronTrackResolutionFilter = {fReader, "Flag_chargedHadronTrackResolutionFilter"};
   TTreeReaderValue<Int_t> Flag_muonBadTrackFilter = {fReader, "Flag_muonBadTrackFilter"};
   TTreeReaderValue<Int_t> Flag_trkPOG_manystripclus53X = {fReader, "Flag_trkPOG_manystripclus53X"};
   TTreeReaderValue<Int_t> Flag_trkPOG_toomanystripclus53X = {fReader, "Flag_trkPOG_toomanystripclus53X"};
   TTreeReaderValue<Int_t> Flag_trkPOG_logErrorTooManyClusters = {fReader, "Flag_trkPOG_logErrorTooManyClusters"};
   TTreeReaderValue<Int_t> Flag_METFilters = {fReader, "Flag_METFilters"};
   TTreeReaderValue<Int_t> Flag_globalSuperTightHalo2016Filter = {fReader, "Flag_globalSuperTightHalo2016Filter"};
   TTreeReaderValue<Int_t> Flag_BadPFMuonFilter = {fReader, "Flag_BadPFMuonFilter"};
   TTreeReaderValue<Int_t> Flag_BadChargedCandidateFilter = {fReader, "Flag_BadChargedCandidateFilter"};
   TTreeReaderValue<Int_t> Flag_ecalBadCalibFilter = {fReader, "Flag_ecalBadCalibFilter"};
   TTreeReaderValue<Int_t> HLT_PFHT650_WideJetMJJ900DEtaJJ1p5 = {fReader, "HLT_PFHT650_WideJetMJJ900DEtaJJ1p5"};
   TTreeReaderValue<Int_t> HLT_PFHT650_WideJetMJJ950DEtaJJ1p5 = {fReader, "HLT_PFHT650_WideJetMJJ950DEtaJJ1p5"};
   TTreeReaderValue<Int_t> HLT_PFHT800 = {fReader, "HLT_PFHT800"};
   TTreeReaderValue<Int_t> HLT_PFHT900 = {fReader, "HLT_PFHT900"};
   TTreeReaderValue<Int_t> HLT_PFJet450 = {fReader, "HLT_PFJet450"};
   TTreeReaderValue<Int_t> HLT_PFJet500 = {fReader, "HLT_PFJet500"};
   TTreeReaderValue<Int_t> HLT_AK8PFJet450 = {fReader, "HLT_AK8PFJet450"};
   TTreeReaderValue<Int_t> HLT_AK8PFJet500 = {fReader, "HLT_AK8PFJet500"};
   TTreeReaderValue<Int_t> HLT_AK8PFJet360_TrimMass30 = {fReader, "HLT_AK8PFJet360_TrimMass30"};
   TTreeReaderValue<Int_t> HLT_AK8PFHT700_TrimR0p1PT0p03Mass50 = {fReader, "HLT_AK8PFHT700_TrimR0p1PT0p03Mass50"};
   TTreeReaderValue<Int_t> HLT_Ele27_eta2p1_WPTight_Gsf = {fReader, "HLT_Ele27_eta2p1_WPTight_Gsf"};
   TTreeReaderValue<Int_t> HLT_Ele27_WPTight_Gsf = {fReader, "HLT_Ele27_WPTight_Gsf"};
   TTreeReaderValue<Int_t> HLT_Ele25_eta2p1_WPTight_Gsf = {fReader, "HLT_Ele25_eta2p1_WPTight_Gsf"};
   TTreeReaderValue<Int_t> HLT_Ele115_CaloIdVT_GsfTrkIdT = {fReader, "HLT_Ele115_CaloIdVT_GsfTrkIdT"};
   TTreeReaderValue<Int_t> HLT_DoubleEle24_22_eta2p1_WPLoose_Gsf = {fReader, "HLT_DoubleEle24_22_eta2p1_WPLoose_Gsf"};
   TTreeReaderValue<Int_t> HLT_DoubleEle33_CaloIdL_MW = {fReader, "HLT_DoubleEle33_CaloIdL_MW"};
   TTreeReaderValue<Int_t> HLT_DoubleEle33_CaloIdL_GsfTrkIdVL_MW = {fReader, "HLT_DoubleEle33_CaloIdL_GsfTrkIdVL_MW"};
   TTreeReaderValue<Int_t> HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZ = {fReader, "HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZ"};
   TTreeReaderValue<Int_t> HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL = {fReader, "HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL"};
   TTreeReaderValue<Int_t> HLT_IsoMu22 = {fReader, "HLT_IsoMu22"};
   TTreeReaderValue<Int_t> HLT_IsoTkMu22 = {fReader, "HLT_IsoTkMu22"};
   TTreeReaderValue<Int_t> HLT_IsoMu24 = {fReader, "HLT_IsoMu24"};
   TTreeReaderValue<Int_t> HLT_IsoTkMu24 = {fReader, "HLT_IsoTkMu24"};
   TTreeReaderValue<Int_t> HLT_IsoMu22_eta2p1 = {fReader, "HLT_IsoMu22_eta2p1"};
   TTreeReaderValue<Int_t> HLT_IsoTkMu22_eta2p1 = {fReader, "HLT_IsoTkMu22_eta2p1"};
   TTreeReaderValue<Int_t> HLT_Mu50 = {fReader, "HLT_Mu50"};
   TTreeReaderValue<Int_t> HLT_TkMu50 = {fReader, "HLT_TkMu50"};
   TTreeReaderValue<Int_t> HLT_DoubleMu33NoFiltersNoVtx = {fReader, "HLT_DoubleMu33NoFiltersNoVtx"};
   TTreeReaderValue<Int_t> HLT_DoubleMu23NoFiltersNoVtxDisplaced = {fReader, "HLT_DoubleMu23NoFiltersNoVtxDisplaced"};
   TTreeReaderValue<Int_t> HLT_Mu30_TkMu11 = {fReader, "HLT_Mu30_TkMu11"};
   TTreeReaderValue<Int_t> HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ = {fReader, "HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ"};
   TTreeReaderValue<Int_t> HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_Mass3p8 = {fReader, "HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_Mass3p8"};
   TTreeReaderValue<Int_t> HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL = {fReader, "HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL"};
   TTreeReaderValue<Int_t> HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ = {fReader, "HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ"};
   TTreeReaderValue<Int_t> HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL = {fReader, "HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL"};
   TTreeReaderValue<Int_t> HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_DZ = {fReader, "HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_DZ"};
   TTreeReaderValue<Int_t> HLT_Ele32_WPTight_Gsf = {fReader, "HLT_Ele32_WPTight_Gsf"};
   TTreeReaderValue<Int_t> HLT_Ele35_WPTight_Gsf = {fReader, "HLT_Ele35_WPTight_Gsf"};
   TTreeReaderValue<Int_t> HLT_IsoMu27 = {fReader, "HLT_IsoMu27"};
   TTreeReaderValue<Int_t> HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL = {fReader, "HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL"};
   TTreeReaderValue<Int_t> HLT_Mu12_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ = {fReader, "HLT_Mu12_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ"};
   TTreeReaderValue<Int_t> HLT_Ele16_Ele12_Ele8_CaloIdL_TrackIdL = {fReader, "HLT_Ele16_Ele12_Ele8_CaloIdL_TrackIdL"};
   TTreeReaderValue<Int_t> HLT_Mu8_DiEle12_CaloIdL_TrackIdL = {fReader, "HLT_Mu8_DiEle12_CaloIdL_TrackIdL"};
   TTreeReaderValue<Int_t> HLT_DiMu9_Ele9_CaloIdL_TrackIdL_DZ = {fReader, "HLT_DiMu9_Ele9_CaloIdL_TrackIdL_DZ"};
   TTreeReaderValue<Int_t> HLT_TripleMu_12_10_5 = {fReader, "HLT_TripleMu_12_10_5"};
   TTreeReaderValue<Int_t> HLT_Ele17_Ele12_CaloIdL_TrackIdL_IsoVL_DZ = {fReader, "HLT_Ele17_Ele12_CaloIdL_TrackIdL_IsoVL_DZ"};
   TTreeReaderValue<Int_t> HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL = {fReader, "HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL"};
   TTreeReaderValue<Int_t> HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ = {fReader, "HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ"};
   TTreeReaderValue<Int_t> HLT_TkMu17_TrkIsoVVL_TkMu8_TrkIsoVVL = {fReader, "HLT_TkMu17_TrkIsoVVL_TkMu8_TrkIsoVVL"};
   TTreeReaderValue<Int_t> HLT_TkMu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ = {fReader, "HLT_TkMu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ"};
   TTreeReaderValue<Int_t> HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_Mass8 = {fReader, "HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_Mass8"};
   TTreeReaderValue<Int_t> HLT_Mu8_TrkIsoVVL_Ele17_CaloIdL_TrackIdL_IsoVL = {fReader, "HLT_Mu8_TrkIsoVVL_Ele17_CaloIdL_TrackIdL_IsoVL"};
   TTreeReaderValue<Int_t> HLT_Mu17_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL = {fReader, "HLT_Mu17_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL"};
   TTreeReaderValue<Int_t> HLT_Mu23_TrkIsoVVL_Ele8_CaloIdL_TrackIdL_IsoVL = {fReader, "HLT_Mu23_TrkIsoVVL_Ele8_CaloIdL_TrackIdL_IsoVL"};
   TTreeReaderValue<Int_t> HLT_Mu23_TrkIsoVVL_Ele8_CaloIdL_TrackIdL_IsoVL_DZ = {fReader, "HLT_Mu23_TrkIsoVVL_Ele8_CaloIdL_TrackIdL_IsoVL_DZ"};
   TTreeReaderValue<Int_t> HLT_TripleMu_10_5_5_DZ = {fReader, "HLT_TripleMu_10_5_5_DZ"};
   TTreeReaderValue<Int_t> HLT_Mu8_DiEle12_CaloIdL_TrackIdL_DZ = {fReader, "HLT_Mu8_DiEle12_CaloIdL_TrackIdL_DZ"};
   TTreeReaderValue<Int_t> HLT_DiMu9_Ele9_CaloIdL_TrackIdL = {fReader, "HLT_DiMu9_Ele9_CaloIdL_TrackIdL"};
   TTreeReaderValue<Int_t> HLT_Ele27_eta2p1_WPLoose_Gsf = {fReader, "HLT_Ele27_eta2p1_WPLoose_Gsf"};
   TTreeReaderValue<Int_t> HLT_Ele32_WPTight_Gsf_L1DoubleEG = {fReader, "HLT_Ele32_WPTight_Gsf_L1DoubleEG"};
   TTreeReaderValue<Int_t> HLT_Photon200 = {fReader, "HLT_Photon200"};
   TTreeReaderValue<Int_t> HLT_Photon175 = {fReader, "HLT_Photon175"};
   TTreeReaderValue<Int_t> HLT_Ele50_CaloIdVT_GsfTrkIdT_PFJet165 = {fReader, "HLT_Ele50_CaloIdVT_GsfTrkIdT_PFJet165"};
   TTreeReaderValue<Int_t> HLT_Ele45_CaloIdVT_GsfTrkIdT_PFJet200_PFJet50 = {fReader, "HLT_Ele45_CaloIdVT_GsfTrkIdT_PFJet200_PFJet50"};
   TTreeReaderValue<Int_t> HLT_Ele27_WP85_Gsf = {fReader, "HLT_Ele27_WP85_Gsf"};
   TTreeReaderValue<Int_t> HLT_Ele32_eta2p1_WPTight_Gsf = {fReader, "HLT_Ele32_eta2p1_WPTight_Gsf"};
   TTreeReaderValue<Int_t> HLT_DoubleMu8_Mass8_PFHT300 = {fReader, "HLT_DoubleMu8_Mass8_PFHT300"};
   TTreeReaderValue<Int_t> HLT_DoubleEle8_CaloIdM_TrackIdM_Mass8_PFHT300 = {fReader, "HLT_DoubleEle8_CaloIdM_TrackIdM_Mass8_PFHT300"};
   TTreeReaderValue<Int_t> HLT_PFHT450_SixJet40_BTagCSV_p056 = {fReader, "HLT_PFHT450_SixJet40_BTagCSV_p056"};
   TTreeReaderValue<Int_t> HLT_PFHT400_SixJet30_DoubleBTagCSV_p056 = {fReader, "HLT_PFHT400_SixJet30_DoubleBTagCSV_p056"};
   TTreeReaderValue<Int_t> HLT_DoubleMediumIsoPFTau35_Trk1_eta2p1_Reg = {fReader, "HLT_DoubleMediumIsoPFTau35_Trk1_eta2p1_Reg"};
   TTreeReaderValue<Int_t> HLT_DoubleMediumCombinedIsoPFTau35_Trk1_eta2p1_Reg = {fReader, "HLT_DoubleMediumCombinedIsoPFTau35_Trk1_eta2p1_Reg"};
   TTreeReaderValue<Int_t> HLT_DoubleMediumChargedIsoPFTau35_Trk1_eta2p1_Reg = {fReader, "HLT_DoubleMediumChargedIsoPFTau35_Trk1_eta2p1_Reg"};
   TTreeReaderValue<Int_t> HLT_DoubleTightChargedIsoPFTau35_Trk1_TightID_eta2p1_Reg = {fReader, "HLT_DoubleTightChargedIsoPFTau35_Trk1_TightID_eta2p1_Reg"};
   TTreeReaderValue<Int_t> HLT_DoubleMediumChargedIsoPFTau40_Trk1_TightID_eta2p1_Reg = {fReader, "HLT_DoubleMediumChargedIsoPFTau40_Trk1_TightID_eta2p1_Reg"};
   TTreeReaderValue<Int_t> HLT_DoubleTightChargedIsoPFTau40_Trk1_eta2p1_Reg = {fReader, "HLT_DoubleTightChargedIsoPFTau40_Trk1_eta2p1_Reg"};
   TTreeReaderValue<Int_t> HLT_DoubleMediumChargedIsoPFTauHPS35_Trk1_eta2p1_Reg = {fReader, "HLT_DoubleMediumChargedIsoPFTauHPS35_Trk1_eta2p1_Reg"};
   TTreeReaderValue<Int_t> HLT_Ele24_eta2p1_WPLoose_Gsf_LooseIsoPFTau20 = {fReader, "HLT_Ele24_eta2p1_WPLoose_Gsf_LooseIsoPFTau20"};
   TTreeReaderValue<Int_t> HLT_Ele24_eta2p1_WPLoose_Gsf_LooseIsoPFTau20_SingleL1 = {fReader, "HLT_Ele24_eta2p1_WPLoose_Gsf_LooseIsoPFTau20_SingleL1"};
   TTreeReaderValue<Int_t> HLT_Ele24_eta2p1_WPLoose_Gsf_LooseIsoPFTau30 = {fReader, "HLT_Ele24_eta2p1_WPLoose_Gsf_LooseIsoPFTau30"};
   TTreeReaderValue<Int_t> HLT_Ele24_eta2p1_WPTight_Gsf_LooseChargedIsoPFTau30_eta2p1_CrossL1 = {fReader, "HLT_Ele24_eta2p1_WPTight_Gsf_LooseChargedIsoPFTau30_eta2p1_CrossL1"};
   TTreeReaderValue<Int_t> HLT_Ele24_eta2p1_WPTight_Gsf_LooseChargedIsoPFTauHPS30_eta2p1_CrossL1 = {fReader, "HLT_Ele24_eta2p1_WPTight_Gsf_LooseChargedIsoPFTauHPS30_eta2p1_CrossL1"};
   TTreeReaderValue<Int_t> HLT_IsoMu19_eta2p1_LooseIsoPFTau20_SingleL1 = {fReader, "HLT_IsoMu19_eta2p1_LooseIsoPFTau20_SingleL1"};
   TTreeReaderValue<Int_t> HLT_IsoMu20_eta2p1_LooseChargedIsoPFTau27_eta2p1_CrossL1 = {fReader, "HLT_IsoMu20_eta2p1_LooseChargedIsoPFTau27_eta2p1_CrossL1"};
   TTreeReaderValue<Int_t> HLT_IsoMu20_eta2p1_LooseChargedIsoPFTauHPS27_eta2p1_CrossL1 = {fReader, "HLT_IsoMu20_eta2p1_LooseChargedIsoPFTauHPS27_eta2p1_CrossL1"};
   TTreeReaderValue<Int_t> HLT_Mu8_Ele8_CaloIdM_TrackIdM_Mass8_PFHT300 = {fReader, "HLT_Mu8_Ele8_CaloIdM_TrackIdM_Mass8_PFHT300"};
   // TTreeReaderValue<Int_t> pvertex_notempty = {fReader, "pvertex_notempty"};
   // TTreeReaderValue<Int_t> nBestVtx = {fReader, "nBestVtx"};
   // TTreeReaderValue<Int_t> npuVertices = {fReader, "npuVertices"};
   // TTreeReaderValue<Double_t> trueInteractions = {fReader, "trueInteractions"};
   // TTreeReaderValue<Int_t> ootnpuVertices = {fReader, "ootnpuVertices"};
   // TTreeReaderValue<Int_t> npuVerticesm1 = {fReader, "npuVerticesm1"};
   // TTreeReaderValue<Int_t> npuVerticesp1 = {fReader, "npuVerticesp1"};
   // TTreeReaderArray<double> pvertex_ndof = {fReader, "pvertex_ndof"};
   // TTreeReaderArray<double> pvertex_dxy = {fReader, "pvertex_dxy"};
   // TTreeReaderArray<double> pvertex_x = {fReader, "pvertex_x"};
   // TTreeReaderArray<double> pvertex_y = {fReader, "pvertex_y"};
   // TTreeReaderArray<double> pvertex_z = {fReader, "pvertex_z"};
   // TTreeReaderArray<double> pvertex_xError = {fReader, "pvertex_xError"};
   // TTreeReaderArray<double> pvertex_yError = {fReader, "pvertex_yError"};
   // TTreeReaderArray<double> pvertex_zError = {fReader, "pvertex_zError"};
   // TTreeReaderArray<double> beamSpot_x0 = {fReader, "beamSpot_x0"};
   // TTreeReaderArray<double> beamSpot_y0 = {fReader, "beamSpot_y0"};
   // TTreeReaderArray<double> beamSpot_z0 = {fReader, "beamSpot_z0"};
   // TTreeReaderArray<double> beamSpot_xWidth = {fReader, "beamSpot_xWidth"};
   // TTreeReaderArray<double> beamSpot_yWidth = {fReader, "beamSpot_yWidth"};
   TTreeReaderArray<double> Muon_pt = {fReader, "Muon_pt"};
   TTreeReaderArray<double> Muon_eta = {fReader, "Muon_eta"};
   TTreeReaderArray<double> Muon_phi = {fReader, "Muon_phi"};
   TTreeReaderArray<double> Muon_energy = {fReader, "Muon_energy"};
   TTreeReaderArray<double> Muon_px = {fReader, "Muon_px"};
   TTreeReaderArray<double> Muon_py = {fReader, "Muon_py"};
   TTreeReaderArray<double> Muon_pz = {fReader, "Muon_pz"};
   // TTreeReaderArray<double> Muon_p = {fReader, "Muon_p"};
   // TTreeReaderArray<double> Muon_dB = {fReader, "Muon_dB"};
   // TTreeReaderArray<double> Muon_pt_it = {fReader, "Muon_pt_it"};
   // TTreeReaderArray<double> Muon_ptErr_it = {fReader, "Muon_ptErr_it"};
   // TTreeReaderArray<double> Muon_pTErrOVpT_it = {fReader, "Muon_pTErrOVpT_it"};
   // TTreeReaderArray<double> Muon_pt_bt = {fReader, "Muon_pt_bt"};
   // TTreeReaderArray<double> Muon_ptErr_bt = {fReader, "Muon_ptErr_bt"};
   TTreeReaderArray<double> Muon_pTErrOVpT_bt = {fReader, "Muon_pTErrOVpT_bt"};
   // TTreeReaderArray<double> Muon_pt_tunePbt = {fReader, "Muon_pt_tunePbt"};
   TTreeReaderArray<double> Muon_charge = {fReader, "Muon_charge"};
   TTreeReaderArray<int> Muon_soft = {fReader, "Muon_soft"};
   TTreeReaderArray<int> Muon_loose = {fReader, "Muon_loose"};
   TTreeReaderArray<int> Muon_medium = {fReader, "Muon_medium"};
   TTreeReaderArray<int> Muon_tight = {fReader, "Muon_tight"};
   TTreeReaderArray<int> Muon_isHighPt = {fReader, "Muon_isHighPt"};
   // TTreeReaderArray<int> Muon_isTrkHighPt = {fReader, "Muon_isTrkHighPt"};
   // TTreeReaderArray<int> Muon_TrkIsoLoose = {fReader, "Muon_TrkIsoLoose"};
   // TTreeReaderArray<int> Muon_TrkIsoTight = {fReader, "Muon_TrkIsoTight"};
   // TTreeReaderArray<int> Muon_TrigLoose = {fReader, "Muon_TrigLoose"};
   // TTreeReaderArray<int> Muon_POGisGood = {fReader, "Muon_POGisGood"};
   TTreeReaderArray<int> Muon_pdgId = {fReader, "Muon_pdgId"};
   TTreeReaderArray<int> Muon_simPdgId = {fReader, "Muon_simPdgId"};
   TTreeReaderArray<int> Muon_simMotherPdgId = {fReader, "Muon_simMotherPdgId"};
   TTreeReaderArray<int> Muon_simFlavour = {fReader, "Muon_simFlavour"};
   // TTreeReaderArray<int> Muon_pf = {fReader, "Muon_pf"};
   TTreeReaderArray<int> Muon_isGlobal = {fReader, "Muon_isGlobal"};
   // TTreeReaderArray<int> Muon_isTrackerMuon = {fReader, "Muon_isTrackerMuon"};
   // TTreeReaderArray<int> Muon_tunePBestTrackType = {fReader, "Muon_tunePBestTrackType"};
   // TTreeReaderArray<double> Muon_isoR04Charged = {fReader, "Muon_isoR04Charged"};
   // TTreeReaderArray<double> Muon_isoR04NeutralHadron = {fReader, "Muon_isoR04NeutralHadron"};
   // TTreeReaderArray<double> Muon_isoR04Photon = {fReader, "Muon_isoR04Photon"};
   // TTreeReaderArray<double> Muon_isoR04PU = {fReader, "Muon_isoR04PU"};
   TTreeReaderArray<double> Muon_relIsoDeltaBetaR04 = {fReader, "Muon_relIsoDeltaBetaR04"};
   // TTreeReaderArray<double> Muon_isoR04CharParPt = {fReader, "Muon_isoR04CharParPt"};
   // TTreeReaderArray<double> Muon_isoR03Charged = {fReader, "Muon_isoR03Charged"};
   // TTreeReaderArray<double> Muon_isoR03NeutralHadron = {fReader, "Muon_isoR03NeutralHadron"};
   // TTreeReaderArray<double> Muon_isoR03Photon = {fReader, "Muon_isoR03Photon"};
   // TTreeReaderArray<double> Muon_isoR03PU = {fReader, "Muon_isoR03PU"};
   // TTreeReaderArray<double> Muon_relIsoDeltaBetaR03 = {fReader, "Muon_relIsoDeltaBetaR03"};
   // TTreeReaderArray<double> Muon_isoR03CharParPt = {fReader, "Muon_isoR03CharParPt"};
   // TTreeReaderArray<double> Muon_trackIso = {fReader, "Muon_trackIso"};
   // TTreeReaderArray<double> Muon_TrackerIso = {fReader, "Muon_TrackerIso"};
   // TTreeReaderArray<double> Muon_ecalIso = {fReader, "Muon_ecalIso"};
   // TTreeReaderArray<double> Muon_hcalIso = {fReader, "Muon_hcalIso"};
   // TTreeReaderArray<double> Muon_caloIso = {fReader, "Muon_caloIso"};
   // TTreeReaderArray<double> Muon_isoSum = {fReader, "Muon_isoSum"};
   // TTreeReaderArray<double> Muon_pfEcalEnergy = {fReader, "Muon_pfEcalEnergy"};
   // TTreeReaderArray<double> Muon_chi2 = {fReader, "Muon_chi2"};
   // TTreeReaderArray<double> Muon_chi2LocalPosition = {fReader, "Muon_chi2LocalPosition"};
   // TTreeReaderArray<double> Muon_matchedStat = {fReader, "Muon_matchedStat"};
   // TTreeReaderArray<double> Muon_validHits = {fReader, "Muon_validHits"};
   // TTreeReaderArray<double> Muon_validHitsInner = {fReader, "Muon_validHitsInner"};
   // TTreeReaderArray<double> Muon_TLayers = {fReader, "Muon_TLayers"};
   // TTreeReaderArray<double> Muon_ndof = {fReader, "Muon_ndof"};
   // TTreeReaderArray<double> Muon_validFraction = {fReader, "Muon_validFraction"};
   // TTreeReaderArray<double> Muon_pixelLayersWithMeasurement = {fReader, "Muon_pixelLayersWithMeasurement"};
   // TTreeReaderArray<double> Muon_qualityhighPurity = {fReader, "Muon_qualityhighPurity"};
   // TTreeReaderArray<double> Muon_trkKink = {fReader, "Muon_trkKink"};
   // TTreeReaderArray<double> Muon_segmentCompatibility = {fReader, "Muon_segmentCompatibility"};
   TTreeReaderArray<double> Muon_dxy_pv = {fReader, "Muon_dxy_pv"};
   TTreeReaderArray<double> Muon_dz_pv = {fReader, "Muon_dz_pv"};
   TTreeReaderArray<double> Muon_dz_bs = {fReader, "Muon_dz_bs"};
   TTreeReaderArray<double> Muon_dxy_bs = {fReader, "Muon_dxy_bs"};
   // TTreeReaderArray<double> Muon_dzError = {fReader, "Muon_dzError"};
   // TTreeReaderArray<double> Muon_dxyError = {fReader, "Muon_dxyError"};
   // TTreeReaderArray<double> Muon_vtx = {fReader, "Muon_vtx"};
   // TTreeReaderArray<double> Muon_vty = {fReader, "Muon_vty"};
   // TTreeReaderArray<double> Muon_vtz = {fReader, "Muon_vtz"};
   TTreeReaderArray<double> Muon_dz_bt = {fReader, "Muon_dz_bt"};
   TTreeReaderArray<double> Muon_dxy_bt = {fReader, "Muon_dxy_bt"};
   TTreeReaderArray<double> Muon_miniIsoRel = {fReader, "Muon_miniIsoRel"};
   TTreeReaderArray<double> Muon_miniIsoCh = {fReader, "Muon_miniIsoCh"};
   TTreeReaderArray<double> Muon_miniIsoNeu = {fReader, "Muon_miniIsoNeu"};
   TTreeReaderArray<double> Muon_miniIsoPUsub = {fReader, "Muon_miniIsoPUsub"};
   // TTreeReaderArray<double> Muon_jetdr = {fReader, "Muon_jetdr"};
   // TTreeReaderArray<double> Muon_jetl1corr = {fReader, "Muon_jetl1corr"};
   // TTreeReaderArray<double> Muon_jetislep = {fReader, "Muon_jetislep"};
   // TTreeReaderArray<int> Muon_jetidx = {fReader, "Muon_jetidx"};
   // TTreeReaderArray<double> Muon_jetpt = {fReader, "Muon_jetpt"};
   TTreeReaderArray<double> Muon_jetptratio = {fReader, "Muon_jetptratio"};
   TTreeReaderArray<double> Muon_jetptratioV2 = {fReader, "Muon_jetptratioV2"};
   // TTreeReaderArray<double> Muon_jetcsv = {fReader, "Muon_jetcsv"};
   // TTreeReaderArray<double> Muon_jetdeepcsv = {fReader, "Muon_jetdeepcsv"};
   // TTreeReaderArray<double> Muon_jetdeepflavour = {fReader, "Muon_jetdeepflavour"};
   TTreeReaderArray<double> Muon_ptrel = {fReader, "Muon_ptrel"};
   TTreeReaderArray<double> Muon_IP3Dsig_it = {fReader, "Muon_IP3Dsig_it"};
   // TTreeReaderArray<double> Muon_pvass = {fReader, "Muon_pvass"};
   // TTreeReaderArray<double> Muon_etarel = {fReader, "Muon_etarel"};
   // TTreeReaderArray<double> Muon_ptOVen = {fReader, "Muon_ptOVen"};
   // TTreeReaderArray<double> Muon_mujet_pfJetProbabilityBJetTag = {fReader, "Muon_mujet_pfJetProbabilityBJetTag"};
   // TTreeReaderArray<double> Muon_mujet_pfCombinedMVABJetTags = {fReader, "Muon_mujet_pfCombinedMVABJetTags"};
   // TTreeReaderArray<double> Muon_mujet_qgl = {fReader, "Muon_mujet_qgl"};
   // TTreeReaderArray<double> Muon_mumass = {fReader, "Muon_mumass"};
   // TTreeReaderArray<double> Muon_mujet_mass = {fReader, "Muon_mujet_mass"};
   // TTreeReaderArray<double> Muon_mujet_Wmass = {fReader, "Muon_mujet_Wmass"};
   // TTreeReaderArray<double> Muon_mujet_Topmass = {fReader, "Muon_mujet_Topmass"};
   // TTreeReaderArray<double> Muon_mujet_WTopmass = {fReader, "Muon_mujet_WTopmass"};
   // TTreeReaderArray<double> Muon_IP3D_val = {fReader, "Muon_IP3D_val"};
   // TTreeReaderArray<double> Muon_IP3D_err = {fReader, "Muon_IP3D_err"};
   TTreeReaderArray<double> Muon_IP3D_sig = {fReader, "Muon_IP3D_sig"};
   // TTreeReaderArray<double> Muon_IP2D_val = {fReader, "Muon_IP2D_val"};
   // TTreeReaderArray<double> Muon_IP2D_err = {fReader, "Muon_IP2D_err"};
   // TTreeReaderArray<double> Muon_IP2D_sig = {fReader, "Muon_IP2D_sig"};
   // TTreeReaderArray<double> Muon_sIP3D_val = {fReader, "Muon_sIP3D_val"};
   // TTreeReaderArray<double> Muon_sIP3D_err = {fReader, "Muon_sIP3D_err"};
   // TTreeReaderArray<double> Muon_sIP3D_sig = {fReader, "Muon_sIP3D_sig"};
   // TTreeReaderArray<double> Muon_sIP2D_val = {fReader, "Muon_sIP2D_val"};
   // TTreeReaderArray<double> Muon_sIP2D_err = {fReader, "Muon_sIP2D_err"};
   // TTreeReaderArray<double> Muon_sIP2D_sig = {fReader, "Muon_sIP2D_sig"};
   // TTreeReaderArray<double> Muon_IP1D_val = {fReader, "Muon_IP1D_val"};
   // TTreeReaderArray<double> Muon_IP1D_err = {fReader, "Muon_IP1D_err"};
   // TTreeReaderArray<double> Muon_IP1D_sig = {fReader, "Muon_IP1D_sig"};
   // TTreeReaderArray<double> Muon_sIP1D_val = {fReader, "Muon_sIP1D_val"};
   // TTreeReaderArray<double> Muon_sIP1D_err = {fReader, "Muon_sIP1D_err"};
   // TTreeReaderArray<double> Muon_sIP1D_sig = {fReader, "Muon_sIP1D_sig"};
   // TTreeReaderArray<double> Muon_lepjetMaxIP3D_val = {fReader, "Muon_lepjetMaxIP3D_val"};
   // TTreeReaderArray<double> Muon_lepjetMaxIP3D_sig = {fReader, "Muon_lepjetMaxIP3D_sig"};
   // TTreeReaderArray<double> Muon_lepjetMaxsIP3D_val = {fReader, "Muon_lepjetMaxsIP3D_val"};
   // TTreeReaderArray<double> Muon_lepjetMaxsIP3D_sig = {fReader, "Muon_lepjetMaxsIP3D_sig"};
   // TTreeReaderArray<double> Muon_lepjetMaxIP2D_val = {fReader, "Muon_lepjetMaxIP2D_val"};
   // TTreeReaderArray<double> Muon_lepjetMaxIP2D_sig = {fReader, "Muon_lepjetMaxIP2D_sig"};
   // TTreeReaderArray<double> Muon_lepjetMaxsIP2D_val = {fReader, "Muon_lepjetMaxsIP2D_val"};
   // TTreeReaderArray<double> Muon_lepjetMaxsIP2D_sig = {fReader, "Muon_lepjetMaxsIP2D_sig"};
   // TTreeReaderArray<double> Muon_lepjetMaxIP1D_val = {fReader, "Muon_lepjetMaxIP1D_val"};
   // TTreeReaderArray<double> Muon_lepjetMaxIP1D_sig = {fReader, "Muon_lepjetMaxIP1D_sig"};
   // TTreeReaderArray<double> Muon_lepjetMaxsIP1D_val = {fReader, "Muon_lepjetMaxsIP1D_val"};
   // TTreeReaderArray<double> Muon_lepjetMaxsIP1D_sig = {fReader, "Muon_lepjetMaxsIP1D_sig"};
   // TTreeReaderArray<double> Muon_lepjetAvIP3D_val = {fReader, "Muon_lepjetAvIP3D_val"};
   // TTreeReaderArray<double> Muon_lepjetAvIP3D_sig = {fReader, "Muon_lepjetAvIP3D_sig"};
   // TTreeReaderArray<double> Muon_lepjetAvsIP3D_val = {fReader, "Muon_lepjetAvsIP3D_val"};
   // TTreeReaderArray<double> Muon_lepjetAvsIP3D_sig = {fReader, "Muon_lepjetAvsIP3D_sig"};
   // TTreeReaderArray<double> Muon_lepjetAvIP2D_val = {fReader, "Muon_lepjetAvIP2D_val"};
   // TTreeReaderArray<double> Muon_lepjetAvIP2D_sig = {fReader, "Muon_lepjetAvIP2D_sig"};
   // TTreeReaderArray<double> Muon_lepjetAvsIP2D_val = {fReader, "Muon_lepjetAvsIP2D_val"};
   // TTreeReaderArray<double> Muon_lepjetAvsIP2D_sig = {fReader, "Muon_lepjetAvsIP2D_sig"};
   // TTreeReaderArray<double> Muon_lepjetAvIP1D_val = {fReader, "Muon_lepjetAvIP1D_val"};
   // TTreeReaderArray<double> Muon_lepjetAvIP1D_sig = {fReader, "Muon_lepjetAvIP1D_sig"};
   // TTreeReaderArray<double> Muon_lepjetAvsIP1D_val = {fReader, "Muon_lepjetAvsIP1D_val"};
   // TTreeReaderArray<double> Muon_lepjetAvsIP1D_sig = {fReader, "Muon_lepjetAvsIP1D_sig"};
   // TTreeReaderArray<double> Muon_lepjetchtrks = {fReader, "Muon_lepjetchtrks"};
   // TTreeReaderArray<double> Muon_lepjetpvchtrks = {fReader, "Muon_lepjetpvchtrks"};
   // TTreeReaderArray<double> Muon_lepjetnonpvchtrks = {fReader, "Muon_lepjetnonpvchtrks"};
   // TTreeReaderArray<double> Muon_lepjetndaus = {fReader, "Muon_lepjetndaus"};
   // TTreeReaderArray<double> Muon_lepjetpvchi2 = {fReader, "Muon_lepjetpvchi2"};
   // TTreeReaderArray<double> Muon_lepjetnumno2trk = {fReader, "Muon_lepjetnumno2trk"};
   TTreeReaderArray<int> Muon_isMatchedToTrigger = {fReader, "Muon_isMatchedToTrigger"};
   TTreeReaderArray<double> patElectron_pt = {fReader, "patElectron_pt"};
   TTreeReaderArray<double> patElectron_eta = {fReader, "patElectron_eta"};
   TTreeReaderArray<double> patElectron_phi = {fReader, "patElectron_phi"};
   TTreeReaderArray<double> patElectron_energy = {fReader, "patElectron_energy"};
   TTreeReaderArray<double> patElectron_px = {fReader, "patElectron_px"};
   TTreeReaderArray<double> patElectron_py = {fReader, "patElectron_py"};
   TTreeReaderArray<double> patElectron_pz = {fReader, "patElectron_pz"};
   TTreeReaderArray<double> patElectron_p = {fReader, "patElectron_p"};
   TTreeReaderArray<double> patElectron_Et = {fReader, "patElectron_Et"};
   TTreeReaderArray<double> patElectron_SCeta = {fReader, "patElectron_SCeta"};
   TTreeReaderArray<double> patElectron_inCrack = {fReader, "patElectron_inCrack"};
   TTreeReaderArray<double> patElectron_energySF = {fReader, "patElectron_energySF"};
   TTreeReaderArray<double> patElectron_ecalEnergyErrPostCorr = {fReader, "patElectron_ecalEnergyErrPostCorr"};
   TTreeReaderArray<double> patElectron_ecalEnergyErrPreCorr = {fReader, "patElectron_ecalEnergyErrPreCorr"};
   TTreeReaderArray<double> patElectron_ecalEnergyPostCorr = {fReader, "patElectron_ecalEnergyPostCorr"};
   TTreeReaderArray<double> patElectron_ecalEnergyPreCorr = {fReader, "patElectron_ecalEnergyPreCorr"};
   TTreeReaderArray<double> patElectron_ecalTrkEnergyErrPostCorr = {fReader, "patElectron_ecalTrkEnergyErrPostCorr"};
   TTreeReaderArray<double> patElectron_ecalTrkEnergyErrPreCorr = {fReader, "patElectron_ecalTrkEnergyErrPreCorr"};
   TTreeReaderArray<double> patElectron_ecalTrkEnergyPostCorr = {fReader, "patElectron_ecalTrkEnergyPostCorr"};
   TTreeReaderArray<double> patElectron_ecalTrkEnergyPreCorr = {fReader, "patElectron_ecalTrkEnergyPreCorr"};
   TTreeReaderArray<double> patElectron_energyScaleDown = {fReader, "patElectron_energyScaleDown"};
   TTreeReaderArray<double> patElectron_energyScaleGainDown = {fReader, "patElectron_energyScaleGainDown"};
   TTreeReaderArray<double> patElectron_energyScaleGainUp = {fReader, "patElectron_energyScaleGainUp"};
   TTreeReaderArray<double> patElectron_energyScaleStatDown = {fReader, "patElectron_energyScaleStatDown"};
   TTreeReaderArray<double> patElectron_energyScaleStatUp = {fReader, "patElectron_energyScaleStatUp"};
   TTreeReaderArray<double> patElectron_energyScaleSystDown = {fReader, "patElectron_energyScaleSystDown"};
   TTreeReaderArray<double> patElectron_energyScaleSystUp = {fReader, "patElectron_energyScaleSystUp"};
   TTreeReaderArray<double> patElectron_energyScaleUp = {fReader, "patElectron_energyScaleUp"};
   TTreeReaderArray<double> patElectron_energyScaleValue = {fReader, "patElectron_energyScaleValue"};
   TTreeReaderArray<double> patElectron_energySigmaDown = {fReader, "patElectron_energySigmaDown"};
   TTreeReaderArray<double> patElectron_energySigmaPhiDown = {fReader, "patElectron_energySigmaPhiDown"};
   TTreeReaderArray<double> patElectron_energySigmaPhiUp = {fReader, "patElectron_energySigmaPhiUp"};
   TTreeReaderArray<double> patElectron_energySigmaRhoDown = {fReader, "patElectron_energySigmaRhoDown"};
   TTreeReaderArray<double> patElectron_energySigmaRhoUp = {fReader, "patElectron_energySigmaRhoUp"};
   TTreeReaderArray<double> patElectron_energySigmaUp = {fReader, "patElectron_energySigmaUp"};
   TTreeReaderArray<double> patElectron_energySigmaValue = {fReader, "patElectron_energySigmaValue"};
   TTreeReaderArray<double> patElectron_energySmearNrSigma = {fReader, "patElectron_energySmearNrSigma"};
   TTreeReaderArray<double> patElectron_charge = {fReader, "patElectron_charge"};
   TTreeReaderArray<double> patElectron_isGsfCtfScPixChargeConsistent = {fReader, "patElectron_isGsfCtfScPixChargeConsistent"};
   TTreeReaderArray<double> patElectron_isGsfScPixChargeConsistent = {fReader, "patElectron_isGsfScPixChargeConsistent"};
   TTreeReaderArray<int> patElectron_isPassVeto = {fReader, "patElectron_isPassVeto"};
   TTreeReaderArray<int> patElectron_isPassLoose = {fReader, "patElectron_isPassLoose"};
   TTreeReaderArray<int> patElectron_isPassMedium = {fReader, "patElectron_isPassMedium"};
   TTreeReaderArray<int> patElectron_isPassTight = {fReader, "patElectron_isPassTight"};
   TTreeReaderArray<int> patElectron_isPassMvaIsowp80 = {fReader, "patElectron_isPassMvaIsowp80"};
   TTreeReaderArray<int> patElectron_isPassMvanonIsowp80 = {fReader, "patElectron_isPassMvanonIsowp80"};
   TTreeReaderArray<int> patElectron_isPassMvaIsowp90 = {fReader, "patElectron_isPassMvaIsowp90"};
   TTreeReaderArray<int> patElectron_isPassMvanonIsowp90 = {fReader, "patElectron_isPassMvanonIsowp90"};
   TTreeReaderArray<int> patElectron_isPassMvaIsowpLoose = {fReader, "patElectron_isPassMvaIsowpLoose"};
   TTreeReaderArray<int> patElectron_isPassMvanonIsowpLoose = {fReader, "patElectron_isPassMvanonIsowpLoose"};
   TTreeReaderArray<float> patElectron_mvaValue_nonIso = {fReader, "patElectron_mvaValue_nonIso"};
   TTreeReaderArray<float> patElectron_mvaCategory_nonIso = {fReader, "patElectron_mvaCategory_nonIso"};
   TTreeReaderArray<float> patElectron_mvaValue_Iso = {fReader, "patElectron_mvaValue_Iso"};
   TTreeReaderArray<float> patElectron_mvaCategory_Iso = {fReader, "patElectron_mvaCategory_Iso"};
   TTreeReaderArray<int> patElectron_isPassHEEPId = {fReader, "patElectron_isPassHEEPId"};
   TTreeReaderArray<int> patElectron_isPassMvaHZZwpLoose = {fReader, "patElectron_isPassMvaHZZwpLoose"};
   TTreeReaderArray<float> patElectron_mvaValue_HZZ = {fReader, "patElectron_mvaValue_HZZ"};
   TTreeReaderArray<float> patElectron_mvaCategory_HZZ = {fReader, "patElectron_mvaCategory_HZZ"};
   TTreeReaderArray<int> patElectron_mvaEleID_Fall17_iso_V2_wp80 = {fReader, "patElectron_mvaEleID_Fall17_iso_V2_wp80"};
   TTreeReaderArray<int> patElectron_mvaEleID_Fall17_noIso_V2_wp80 = {fReader, "patElectron_mvaEleID_Fall17_noIso_V2_wp80"};
   TTreeReaderArray<int> patElectron_mvaEleID_Fall17_iso_V2_wp90 = {fReader, "patElectron_mvaEleID_Fall17_iso_V2_wp90"};
   TTreeReaderArray<int> patElectron_mvaEleID_Fall17_noIso_V2_wp90 = {fReader, "patElectron_mvaEleID_Fall17_noIso_V2_wp90"};
   TTreeReaderArray<int> patElectron_mvaEleID_Fall17_iso_V2_wpLoose = {fReader, "patElectron_mvaEleID_Fall17_iso_V2_wpLoose"};
   TTreeReaderArray<int> patElectron_mvaEleID_Fall17_noIso_V2_wpLoose = {fReader, "patElectron_mvaEleID_Fall17_noIso_V2_wpLoose"};
   TTreeReaderArray<float> patElectron_ElectronMVAEstimatorRun2Fall17NoIsoV2Values = {fReader, "patElectron_ElectronMVAEstimatorRun2Fall17NoIsoV2Values"};
   TTreeReaderArray<float> patElectron_ElectronMVAEstimatorRun2Fall17NoIsoV2Categories = {fReader, "patElectron_ElectronMVAEstimatorRun2Fall17NoIsoV2Categories"};
   TTreeReaderArray<float> patElectron_ElectronMVAEstimatorRun2Fall17IsoV2Values = {fReader, "patElectron_ElectronMVAEstimatorRun2Fall17IsoV2Values"};
   TTreeReaderArray<float> patElectron_ElectronMVAEstimatorRun2Fall17IsoV2Categories = {fReader, "patElectron_ElectronMVAEstimatorRun2Fall17IsoV2Categories"};
   TTreeReaderArray<int> patElectron_mvaEleID_Spring16_GeneralPurpose_V1_wp80 = {fReader, "patElectron_mvaEleID_Spring16_GeneralPurpose_V1_wp80"};
   TTreeReaderArray<int> patElectron_mvaEleID_Spring16_GeneralPurpose_V1_wp90 = {fReader, "patElectron_mvaEleID_Spring16_GeneralPurpose_V1_wp90"};
   TTreeReaderArray<float> patElectron_MVAValue_ElectronMVAEstimatorRun2Spring16GeneralPurposeV1 = {fReader, "patElectron_MVAValue_ElectronMVAEstimatorRun2Spring16GeneralPurposeV1"};
   TTreeReaderArray<int> patElectron_cutBasedElectronID_Fall17_94X_V2_loose = {fReader, "patElectron_cutBasedElectronID_Fall17_94X_V2_loose"};
   TTreeReaderArray<int> patElectron_cutBasedElectronID_Fall17_94X_V2_medium = {fReader, "patElectron_cutBasedElectronID_Fall17_94X_V2_medium"};
   TTreeReaderArray<int> patElectron_cutBasedElectronID_Fall17_94X_V2_tight = {fReader, "patElectron_cutBasedElectronID_Fall17_94X_V2_tight"};
   TTreeReaderArray<int> patElectron_cutBasedElectronID_Fall17_94X_V2_veto = {fReader, "patElectron_cutBasedElectronID_Fall17_94X_V2_veto"};
   TTreeReaderArray<int> patElectron_cutBasedElectronID_Fall17_94X_V1_loose = {fReader, "patElectron_cutBasedElectronID_Fall17_94X_V1_loose"};
   TTreeReaderArray<int> patElectron_cutBasedElectronID_Fall17_94X_V1_medium = {fReader, "patElectron_cutBasedElectronID_Fall17_94X_V1_medium"};
   TTreeReaderArray<int> patElectron_cutBasedElectronID_Fall17_94X_V1_tight = {fReader, "patElectron_cutBasedElectronID_Fall17_94X_V1_tight"};
   TTreeReaderArray<int> patElectron_cutBasedElectronID_Fall17_94X_V1_veto = {fReader, "patElectron_cutBasedElectronID_Fall17_94X_V1_veto"};
   TTreeReaderArray<int> patElectron_cutBasedElectronID_Summer16_80X_V1_loose = {fReader, "patElectron_cutBasedElectronID_Summer16_80X_V1_loose"};
   TTreeReaderArray<int> patElectron_cutBasedElectronID_Summer16_80X_V1_medium = {fReader, "patElectron_cutBasedElectronID_Summer16_80X_V1_medium"};
   TTreeReaderArray<int> patElectron_cutBasedElectronID_Summer16_80X_V1_tight = {fReader, "patElectron_cutBasedElectronID_Summer16_80X_V1_tight"};
   TTreeReaderArray<int> patElectron_cutBasedElectronID_Summer16_80X_V1_veto = {fReader, "patElectron_cutBasedElectronID_Summer16_80X_V1_veto"};
   TTreeReaderArray<int> patElectron_mvaEleID_Fall17_iso_V1_wp80 = {fReader, "patElectron_mvaEleID_Fall17_iso_V1_wp80"};
   TTreeReaderArray<int> patElectron_mvaEleID_Fall17_iso_V1_wp90 = {fReader, "patElectron_mvaEleID_Fall17_iso_V1_wp90"};
   TTreeReaderArray<int> patElectron_mvaEleID_Spring16_HZZ_V1_wpLoose_ = {fReader, "patElectron_mvaEleID_Spring16_HZZ_V1_wpLoose_"};
   TTreeReaderArray<int> patElectron_mvaEleID_Fall17_iso_V1_wpLoose = {fReader, "patElectron_mvaEleID_Fall17_iso_V1_wpLoose"};
   TTreeReaderArray<int> patElectron_heepElectronID_HEEPV70 = {fReader, "patElectron_heepElectronID_HEEPV70"};
   TTreeReaderArray<int> patElectron_pdgId = {fReader, "patElectron_pdgId"};
   TTreeReaderArray<int> patElectron_isEcalDriven = {fReader, "patElectron_isEcalDriven"};
   TTreeReaderArray<float> patElectron_ElectronMVAEstimatorRun2Spring16HZZV1Values = {fReader, "patElectron_ElectronMVAEstimatorRun2Spring16HZZV1Values"};
   TTreeReaderArray<float> patElectron_ElectronMVAEstimatorRun2Spring16HZZV1Categories_ = {fReader, "patElectron_ElectronMVAEstimatorRun2Spring16HZZV1Categories_"};
   TTreeReaderArray<double> patElectron_isoChargedHadrons = {fReader, "patElectron_isoChargedHadrons"};
   TTreeReaderArray<double> patElectron_isoNeutralHadrons = {fReader, "patElectron_isoNeutralHadrons"};
   TTreeReaderArray<double> patElectron_isoPhotons = {fReader, "patElectron_isoPhotons"};
   TTreeReaderArray<double> patElectron_isoPU = {fReader, "patElectron_isoPU"};
   TTreeReaderArray<double> patElectron_relIsoDeltaBeta = {fReader, "patElectron_relIsoDeltaBeta"};
   TTreeReaderArray<double> patElectron_relIsoRhoEA = {fReader, "patElectron_relIsoRhoEA"};
   TTreeReaderArray<double> patElectron_relIsoRhoEA_Update = {fReader, "patElectron_relIsoRhoEA_Update"};
   TTreeReaderArray<double> patElectron_dr03EcalRecHitSumEt = {fReader, "patElectron_dr03EcalRecHitSumEt"};
   TTreeReaderArray<double> patElectron_dr03HcalDepth1TowerSumEt = {fReader, "patElectron_dr03HcalDepth1TowerSumEt"};
   TTreeReaderArray<double> patElectron_isolPtTracks = {fReader, "patElectron_isolPtTracks"};
   TTreeReaderArray<double> patElectron_ecalPFClusterIso = {fReader, "patElectron_ecalPFClusterIso"};
   TTreeReaderArray<double> patElectron_hcalPFClusterIso = {fReader, "patElectron_hcalPFClusterIso"};
   TTreeReaderArray<double> patElectron_dEtaIn = {fReader, "patElectron_dEtaIn"};
   TTreeReaderArray<double> patElectron_dPhiIn = {fReader, "patElectron_dPhiIn"};
   TTreeReaderArray<double> patElectron_full5x5_sigmaIetaIeta = {fReader, "patElectron_full5x5_sigmaIetaIeta"};
   TTreeReaderArray<double> patElectron_full5x5_e2x5Max = {fReader, "patElectron_full5x5_e2x5Max"};
   TTreeReaderArray<double> patElectron_full5x5_e5x5 = {fReader, "patElectron_full5x5_e5x5"};
   TTreeReaderArray<double> patElectron_full5x5_e1x5 = {fReader, "patElectron_full5x5_e1x5"};
   TTreeReaderArray<double> patElectron_hOverE = {fReader, "patElectron_hOverE"};
   TTreeReaderArray<double> patElectron_ooEmooP = {fReader, "patElectron_ooEmooP"};
   TTreeReaderArray<double> patElectron_passConversionVeto = {fReader, "patElectron_passConversionVeto"};
   TTreeReaderArray<double> patElectron_expectedMissingInnerHits = {fReader, "patElectron_expectedMissingInnerHits"};
   TTreeReaderArray<double> patElectron_gsfTrack_ndof = {fReader, "patElectron_gsfTrack_ndof"};
   TTreeReaderArray<double> patElectron_gsfTrack_normChi2 = {fReader, "patElectron_gsfTrack_normChi2"};
   TTreeReaderArray<double> patElectron_gsfTrack_dz_pv = {fReader, "patElectron_gsfTrack_dz_pv"};
   TTreeReaderArray<double> patElectron_gsfTrack_dxy_pv = {fReader, "patElectron_gsfTrack_dxy_pv"};
   TTreeReaderArray<double> patElectron_d0 = {fReader, "patElectron_d0"};
   TTreeReaderArray<double> patElectron_dzError = {fReader, "patElectron_dzError"};
   TTreeReaderArray<double> patElectron_dxyError = {fReader, "patElectron_dxyError"};
   TTreeReaderArray<double> patElectron_gsfTrack_vtx = {fReader, "patElectron_gsfTrack_vtx"};
   TTreeReaderArray<double> patElectron_gsfTrack_vty = {fReader, "patElectron_gsfTrack_vty"};
   TTreeReaderArray<double> patElectron_gsfTrack_vtz = {fReader, "patElectron_gsfTrack_vtz"};
   TTreeReaderArray<double> patElectron_miniIsoRel = {fReader, "patElectron_miniIsoRel"};
   TTreeReaderArray<double> patElectron_miniIsoCh = {fReader, "patElectron_miniIsoCh"};
   TTreeReaderArray<double> patElectron_miniIsoNeu = {fReader, "patElectron_miniIsoNeu"};
   TTreeReaderArray<double> patElectron_miniIsoPUsub = {fReader, "patElectron_miniIsoPUsub"};
   TTreeReaderArray<double> patElectron_jetdr = {fReader, "patElectron_jetdr"};
   TTreeReaderArray<double> patElectron_jetl1corr = {fReader, "patElectron_jetl1corr"};
   TTreeReaderArray<double> patElectron_jetislep = {fReader, "patElectron_jetislep"};
   TTreeReaderArray<int> patElectron_jetidx = {fReader, "patElectron_jetidx"};
   TTreeReaderArray<double> patElectron_jetpt = {fReader, "patElectron_jetpt"};
   TTreeReaderArray<double> patElectron_jetptratio = {fReader, "patElectron_jetptratio"};
   TTreeReaderArray<double> patElectron_jetptratioV2 = {fReader, "patElectron_jetptratioV2"};
   TTreeReaderArray<double> patElectron_jetcsv = {fReader, "patElectron_jetcsv"};
   TTreeReaderArray<double> patElectron_jetdeepcsv = {fReader, "patElectron_jetdeepcsv"};
   TTreeReaderArray<double> patElectron_jetdeepflavour = {fReader, "patElectron_jetdeepflavour"};
   TTreeReaderArray<double> patElectron_ptrel = {fReader, "patElectron_ptrel"};
   TTreeReaderArray<double> patElectron_IP3Dsig = {fReader, "patElectron_IP3Dsig"};
   TTreeReaderArray<double> patElectron_eleMVASpring15NonTrig25ns = {fReader, "patElectron_eleMVASpring15NonTrig25ns"};
   TTreeReaderArray<double> patElectron_eleMVASpring15NonTrig25ns_VL = {fReader, "patElectron_eleMVASpring15NonTrig25ns_VL"};
   TTreeReaderArray<double> patElectron_pvass = {fReader, "patElectron_pvass"};
   TTreeReaderArray<double> patElectron_etarel = {fReader, "patElectron_etarel"};
   TTreeReaderArray<double> patElectron_ptOVen = {fReader, "patElectron_ptOVen"};
   TTreeReaderArray<double> patElectron_elejet_pfJetProbabilityBJetTag = {fReader, "patElectron_elejet_pfJetProbabilityBJetTag"};
   TTreeReaderArray<double> patElectron_elejet_pfCombinedMVABJetTags = {fReader, "patElectron_elejet_pfCombinedMVABJetTags"};
   TTreeReaderArray<double> patElectron_elejet_qgl = {fReader, "patElectron_elejet_qgl"};
   TTreeReaderArray<double> patElectron_elemass = {fReader, "patElectron_elemass"};
   TTreeReaderArray<double> patElectron_elejet_mass = {fReader, "patElectron_elejet_mass"};
   TTreeReaderArray<double> patElectron_elejet_Wmass = {fReader, "patElectron_elejet_Wmass"};
   TTreeReaderArray<double> patElectron_elejet_Topmass = {fReader, "patElectron_elejet_Topmass"};
   TTreeReaderArray<double> patElectron_elejet_WTopmass = {fReader, "patElectron_elejet_WTopmass"};
   TTreeReaderArray<double> patElectron_IP3D_val = {fReader, "patElectron_IP3D_val"};
   TTreeReaderArray<double> patElectron_IP3D_err = {fReader, "patElectron_IP3D_err"};
   TTreeReaderArray<double> patElectron_IP3D_sig = {fReader, "patElectron_IP3D_sig"};
   TTreeReaderArray<double> patElectron_IP2D_val = {fReader, "patElectron_IP2D_val"};
   TTreeReaderArray<double> patElectron_IP2D_err = {fReader, "patElectron_IP2D_err"};
   TTreeReaderArray<double> patElectron_IP2D_sig = {fReader, "patElectron_IP2D_sig"};
   TTreeReaderArray<double> patElectron_sIP3D_val = {fReader, "patElectron_sIP3D_val"};
   TTreeReaderArray<double> patElectron_sIP3D_err = {fReader, "patElectron_sIP3D_err"};
   TTreeReaderArray<double> patElectron_sIP3D_sig = {fReader, "patElectron_sIP3D_sig"};
   TTreeReaderArray<double> patElectron_sIP2D_val = {fReader, "patElectron_sIP2D_val"};
   TTreeReaderArray<double> patElectron_sIP2D_err = {fReader, "patElectron_sIP2D_err"};
   TTreeReaderArray<double> patElectron_sIP2D_sig = {fReader, "patElectron_sIP2D_sig"};
   TTreeReaderArray<double> patElectron_IP1D_val = {fReader, "patElectron_IP1D_val"};
   TTreeReaderArray<double> patElectron_IP1D_err = {fReader, "patElectron_IP1D_err"};
   TTreeReaderArray<double> patElectron_IP1D_sig = {fReader, "patElectron_IP1D_sig"};
   TTreeReaderArray<double> patElectron_sIP1D_val = {fReader, "patElectron_sIP1D_val"};
   TTreeReaderArray<double> patElectron_sIP1D_err = {fReader, "patElectron_sIP1D_err"};
   TTreeReaderArray<double> patElectron_sIP1D_sig = {fReader, "patElectron_sIP1D_sig"};
   TTreeReaderArray<double> patElectron_lepjetMaxIP3D_val = {fReader, "patElectron_lepjetMaxIP3D_val"};
   TTreeReaderArray<double> patElectron_lepjetMaxIP3D_sig = {fReader, "patElectron_lepjetMaxIP3D_sig"};
   TTreeReaderArray<double> patElectron_lepjetMaxsIP3D_val = {fReader, "patElectron_lepjetMaxsIP3D_val"};
   TTreeReaderArray<double> patElectron_lepjetMaxsIP3D_sig = {fReader, "patElectron_lepjetMaxsIP3D_sig"};
   TTreeReaderArray<double> patElectron_lepjetMaxIP2D_val = {fReader, "patElectron_lepjetMaxIP2D_val"};
   TTreeReaderArray<double> patElectron_lepjetMaxIP2D_sig = {fReader, "patElectron_lepjetMaxIP2D_sig"};
   TTreeReaderArray<double> patElectron_lepjetMaxsIP2D_val = {fReader, "patElectron_lepjetMaxsIP2D_val"};
   TTreeReaderArray<double> patElectron_lepjetMaxsIP2D_sig = {fReader, "patElectron_lepjetMaxsIP2D_sig"};
   TTreeReaderArray<double> patElectron_lepjetMaxIP1D_val = {fReader, "patElectron_lepjetMaxIP1D_val"};
   TTreeReaderArray<double> patElectron_lepjetMaxIP1D_sig = {fReader, "patElectron_lepjetMaxIP1D_sig"};
   TTreeReaderArray<double> patElectron_lepjetMaxsIP1D_val = {fReader, "patElectron_lepjetMaxsIP1D_val"};
   TTreeReaderArray<double> patElectron_lepjetMaxsIP1D_sig = {fReader, "patElectron_lepjetMaxsIP1D_sig"};
   TTreeReaderArray<double> patElectron_lepjetAvIP3D_val = {fReader, "patElectron_lepjetAvIP3D_val"};
   TTreeReaderArray<double> patElectron_lepjetAvIP3D_sig = {fReader, "patElectron_lepjetAvIP3D_sig"};
   TTreeReaderArray<double> patElectron_lepjetAvsIP3D_val = {fReader, "patElectron_lepjetAvsIP3D_val"};
   TTreeReaderArray<double> patElectron_lepjetAvsIP3D_sig = {fReader, "patElectron_lepjetAvsIP3D_sig"};
   TTreeReaderArray<double> patElectron_lepjetAvIP2D_val = {fReader, "patElectron_lepjetAvIP2D_val"};
   TTreeReaderArray<double> patElectron_lepjetAvIP2D_sig = {fReader, "patElectron_lepjetAvIP2D_sig"};
   TTreeReaderArray<double> patElectron_lepjetAvsIP2D_val = {fReader, "patElectron_lepjetAvsIP2D_val"};
   TTreeReaderArray<double> patElectron_lepjetAvsIP2D_sig = {fReader, "patElectron_lepjetAvsIP2D_sig"};
   TTreeReaderArray<double> patElectron_lepjetAvIP1D_val = {fReader, "patElectron_lepjetAvIP1D_val"};
   TTreeReaderArray<double> patElectron_lepjetAvIP1D_sig = {fReader, "patElectron_lepjetAvIP1D_sig"};
   TTreeReaderArray<double> patElectron_lepjetAvsIP1D_val = {fReader, "patElectron_lepjetAvsIP1D_val"};
   TTreeReaderArray<double> patElectron_lepjetAvsIP1D_sig = {fReader, "patElectron_lepjetAvsIP1D_sig"};
   TTreeReaderArray<double> patElectron_lepjetchtrks = {fReader, "patElectron_lepjetchtrks"};
   TTreeReaderArray<double> patElectron_lepjetpvchtrks = {fReader, "patElectron_lepjetpvchtrks"};
   TTreeReaderArray<double> patElectron_lepjetnonpvchtrks = {fReader, "patElectron_lepjetnonpvchtrks"};
   TTreeReaderArray<double> patElectron_lepjetndaus = {fReader, "patElectron_lepjetndaus"};
   TTreeReaderArray<double> patElectron_lepjetpvchi2 = {fReader, "patElectron_lepjetpvchi2"};
   TTreeReaderArray<double> patElectron_lepjetnumno2trk = {fReader, "patElectron_lepjetnumno2trk"};
   // TTreeReaderArray<int> patElectron_gen_isPromptFinalState = {fReader, "patElectron_gen_isPromptFinalState"};
   // TTreeReaderArray<int> patElectron_gen_isDirectPromptTauDecayProductFinalState = {fReader, "patElectron_gen_isDirectPromptTauDecayProductFinalState"};
   TTreeReaderArray<int> patElectron_isMatchedToTrigger = {fReader, "patElectron_isMatchedToTrigger"};
   TTreeReaderArray<double> Tau_pt = {fReader, "Tau_pt"};
   TTreeReaderArray<double> Tau_eta = {fReader, "Tau_eta"};
   TTreeReaderArray<double> Tau_phi = {fReader, "Tau_phi"};
   TTreeReaderArray<double> Tau_energy = {fReader, "Tau_energy"};
   TTreeReaderArray<double> Tau_px = {fReader, "Tau_px"};
   TTreeReaderArray<double> Tau_py = {fReader, "Tau_py"};
   TTreeReaderArray<double> Tau_pz = {fReader, "Tau_pz"};
   TTreeReaderArray<double> Tau_p = {fReader, "Tau_p"};
   TTreeReaderArray<double> Tau_leadChargedCandPt = {fReader, "Tau_leadChargedCandPt"};
   TTreeReaderArray<double> Tau_leadChargedCandEta = {fReader, "Tau_leadChargedCandEta"};
   TTreeReaderArray<double> Tau_leadChargedCandPhi = {fReader, "Tau_leadChargedCandPhi"};
   TTreeReaderArray<double> Tau_leadChargedCandE = {fReader, "Tau_leadChargedCandE"};
   TTreeReaderArray<double> Tau_leadChargedCandTrack_pt = {fReader, "Tau_leadChargedCandTrack_pt"};
   TTreeReaderArray<double> Tau_leadChargedCandTrack_ptError = {fReader, "Tau_leadChargedCandTrack_ptError"};
   TTreeReaderArray<double> Tau_charge = {fReader, "Tau_charge"};
   TTreeReaderArray<double> Tau_leadChargedCandCharge = {fReader, "Tau_leadChargedCandCharge"};
   TTreeReaderArray<int> Tau_decayModeFinding = {fReader, "Tau_decayModeFinding"};
   TTreeReaderArray<int> Tau_decayMode = {fReader, "Tau_decayMode"};
   TTreeReaderArray<int> Tau_decayModeFindingNewDMs = {fReader, "Tau_decayModeFindingNewDMs"};
   TTreeReaderArray<int> Tau_againstMuonLoose3 = {fReader, "Tau_againstMuonLoose3"};
   TTreeReaderArray<int> Tau_againstMuonTight3 = {fReader, "Tau_againstMuonTight3"};
   TTreeReaderArray<int> Tau_againstElectronVLooseMVA6 = {fReader, "Tau_againstElectronVLooseMVA6"};
   TTreeReaderArray<int> Tau_againstElectronLooseMVA6 = {fReader, "Tau_againstElectronLooseMVA6"};
   TTreeReaderArray<int> Tau_againstElectronMediumMVA6 = {fReader, "Tau_againstElectronMediumMVA6"};
   TTreeReaderArray<int> Tau_againstElectronTightMVA6 = {fReader, "Tau_againstElectronTightMVA6"};
   TTreeReaderArray<double> Tau_chargedIsoPtSum = {fReader, "Tau_chargedIsoPtSum"};
   TTreeReaderArray<double> Tau_neutralIsoPtSum = {fReader, "Tau_neutralIsoPtSum"};
   TTreeReaderArray<double> Tau_puCorrPtSum = {fReader, "Tau_puCorrPtSum"};
   TTreeReaderArray<int> Tau_byLooseIsolationMVArun2v1DBdR03oldDMwLT = {fReader, "Tau_byLooseIsolationMVArun2v1DBdR03oldDMwLT"};
   TTreeReaderArray<int> Tau_byMediumIsolationMVArun2v1DBdR03oldDMwLT = {fReader, "Tau_byMediumIsolationMVArun2v1DBdR03oldDMwLT"};
   TTreeReaderArray<double> Tau_byIsolationMVArun2017v2DBoldDMdR0p3wLTraw2017 = {fReader, "Tau_byIsolationMVArun2017v2DBoldDMdR0p3wLTraw2017"};
   TTreeReaderArray<int> Tau_byVVLooseIsolationMVArun2017v2DBoldDMdR0p3wLT2017 = {fReader, "Tau_byVVLooseIsolationMVArun2017v2DBoldDMdR0p3wLT2017"};
   TTreeReaderArray<int> Tau_byVLooseIsolationMVArun2017v2DBoldDMdR0p3wLT2017 = {fReader, "Tau_byVLooseIsolationMVArun2017v2DBoldDMdR0p3wLT2017"};
   TTreeReaderArray<int> Tau_byLooseIsolationMVArun2017v2DBoldDMdR0p3wLT2017 = {fReader, "Tau_byLooseIsolationMVArun2017v2DBoldDMdR0p3wLT2017"};
   TTreeReaderArray<int> Tau_byMediumIsolationMVArun2017v2DBoldDMdR0p3wLT2017 = {fReader, "Tau_byMediumIsolationMVArun2017v2DBoldDMdR0p3wLT2017"};
   TTreeReaderArray<int> Tau_byTightIsolationMVArun2017v2DBoldDMdR0p3wLT2017 = {fReader, "Tau_byTightIsolationMVArun2017v2DBoldDMdR0p3wLT2017"};
   TTreeReaderArray<int> Tau_byVTightIsolationMVArun2017v2DBoldDMdR0p3wLT2017 = {fReader, "Tau_byVTightIsolationMVArun2017v2DBoldDMdR0p3wLT2017"};
   TTreeReaderArray<int> Tau_byVVTightIsolationMVArun2017v2DBoldDMdR0p3wLT2017 = {fReader, "Tau_byVVTightIsolationMVArun2017v2DBoldDMdR0p3wLT2017"};
   TTreeReaderArray<double> Tau_byDeepTau2017v2p1VSjetraw = {fReader, "Tau_byDeepTau2017v2p1VSjetraw"};
   TTreeReaderArray<int> Tau_byVVVLooseDeepTau2017v2p1VSjet = {fReader, "Tau_byVVVLooseDeepTau2017v2p1VSjet"};
   TTreeReaderArray<int> Tau_byVVLooseDeepTau2017v2p1VSjet = {fReader, "Tau_byVVLooseDeepTau2017v2p1VSjet"};
   TTreeReaderArray<int> Tau_byVLooseDeepTau2017v2p1VSjet = {fReader, "Tau_byVLooseDeepTau2017v2p1VSjet"};
   TTreeReaderArray<int> Tau_byLooseDeepTau2017v2p1VSjet = {fReader, "Tau_byLooseDeepTau2017v2p1VSjet"};
   TTreeReaderArray<int> Tau_byMediumDeepTau2017v2p1VSjet = {fReader, "Tau_byMediumDeepTau2017v2p1VSjet"};
   TTreeReaderArray<int> Tau_byTightDeepTau2017v2p1VSjet = {fReader, "Tau_byTightDeepTau2017v2p1VSjet"};
   TTreeReaderArray<int> Tau_byVTightDeepTau2017v2p1VSjet = {fReader, "Tau_byVTightDeepTau2017v2p1VSjet"};
   TTreeReaderArray<int> Tau_byVVTightDeepTau2017v2p1VSjet = {fReader, "Tau_byVVTightDeepTau2017v2p1VSjet"};
   TTreeReaderArray<double> Tau_byDeepTau2017v2p1VSmuraw = {fReader, "Tau_byDeepTau2017v2p1VSmuraw"};
   TTreeReaderArray<int> Tau_byVLooseDeepTau2017v2p1VSmu = {fReader, "Tau_byVLooseDeepTau2017v2p1VSmu"};
   TTreeReaderArray<int> Tau_byLooseDeepTau2017v2p1VSmu = {fReader, "Tau_byLooseDeepTau2017v2p1VSmu"};
   TTreeReaderArray<int> Tau_byMediumDeepTau2017v2p1VSmu = {fReader, "Tau_byMediumDeepTau2017v2p1VSmu"};
   TTreeReaderArray<int> Tau_byTightDeepTau2017v2p1VSmu = {fReader, "Tau_byTightDeepTau2017v2p1VSmu"};
   TTreeReaderArray<double> Tau_byDeepTau2017v2p1VSeraw = {fReader, "Tau_byDeepTau2017v2p1VSeraw"};
   TTreeReaderArray<int> Tau_byVVVLooseDeepTau2017v2p1VSe = {fReader, "Tau_byVVVLooseDeepTau2017v2p1VSe"};
   TTreeReaderArray<int> Tau_byVVLooseDeepTau2017v2p1VSe = {fReader, "Tau_byVVLooseDeepTau2017v2p1VSe"};
   TTreeReaderArray<int> Tau_byVLooseDeepTau2017v2p1VSe = {fReader, "Tau_byVLooseDeepTau2017v2p1VSe"};
   TTreeReaderArray<int> Tau_byLooseDeepTau2017v2p1VSe = {fReader, "Tau_byLooseDeepTau2017v2p1VSe"};
   TTreeReaderArray<int> Tau_byMediumDeepTau2017v2p1VSe = {fReader, "Tau_byMediumDeepTau2017v2p1VSe"};
   TTreeReaderArray<int> Tau_byTightDeepTau2017v2p1VSe = {fReader, "Tau_byTightDeepTau2017v2p1VSe"};
   TTreeReaderArray<int> Tau_byVTightDeepTau2017v2p1VSe = {fReader, "Tau_byVTightDeepTau2017v2p1VSe"};
   TTreeReaderArray<int> Tau_byVVTightDeepTau2017v2p1VSe = {fReader, "Tau_byVVTightDeepTau2017v2p1VSe"};
   TTreeReaderArray<double> Tau_nProngs = {fReader, "Tau_nProngs"};
   TTreeReaderArray<double> Tau_leadChargedCandNdof = {fReader, "Tau_leadChargedCandNdof"};
   TTreeReaderArray<double> Tau_leadChargedCandChi2 = {fReader, "Tau_leadChargedCandChi2"};
   TTreeReaderArray<double> Tau_leadChargedCandValidHits = {fReader, "Tau_leadChargedCandValidHits"};
   TTreeReaderArray<double> Tau_defaultDxy = {fReader, "Tau_defaultDxy"};
   TTreeReaderArray<double> Tau_defaultDxyError = {fReader, "Tau_defaultDxyError"};
   TTreeReaderArray<double> Tau_defaultDxySig = {fReader, "Tau_defaultDxySig"};
   TTreeReaderArray<double> Tau_packedLeadTauCand_dxy = {fReader, "Tau_packedLeadTauCand_dxy"};
   TTreeReaderArray<double> Tau_packedLeadTauCand_dz = {fReader, "Tau_packedLeadTauCand_dz"};
   TTreeReaderArray<double> Tau_packedLeadTauCand_dxyError = {fReader, "Tau_packedLeadTauCand_dxyError"};
   TTreeReaderArray<double> Tau_packedLeadTauCand_dzError = {fReader, "Tau_packedLeadTauCand_dzError"};
   TTreeReaderArray<double> Tau_defaultFlightLengthX = {fReader, "Tau_defaultFlightLengthX"};
   TTreeReaderArray<double> Tau_defaultFlightLengthY = {fReader, "Tau_defaultFlightLengthY"};
   TTreeReaderArray<double> Tau_defaultFlightLengthZ = {fReader, "Tau_defaultFlightLengthZ"};
   TTreeReaderArray<double> Tau_defaultFlightLengthSig = {fReader, "Tau_defaultFlightLengthSig"};
   TTreeReaderArray<double> Tau_default_PCAx_pv = {fReader, "Tau_default_PCAx_pv"};
   TTreeReaderArray<double> Tau_default_PCAy_pv = {fReader, "Tau_default_PCAy_pv"};
   TTreeReaderArray<double> Tau_default_PCAz_pv = {fReader, "Tau_default_PCAz_pv"};
   TTreeReaderArray<double> Tau_leadChargedCandDz_pv = {fReader, "Tau_leadChargedCandDz_pv"};
   TTreeReaderArray<double> Tau_leadChargedCandDxy_pv = {fReader, "Tau_leadChargedCandDxy_pv"};
   TTreeReaderArray<double> Tau_leadChargedCandDz_bs = {fReader, "Tau_leadChargedCandDz_bs"};
   TTreeReaderArray<double> Tau_leadChargedCandDxy_bs = {fReader, "Tau_leadChargedCandDxy_bs"};
   TTreeReaderArray<double> Tau_leadChargedCandDzError = {fReader, "Tau_leadChargedCandDzError"};
   TTreeReaderArray<double> Tau_leadChargedCandDxyError = {fReader, "Tau_leadChargedCandDxyError"};
   TTreeReaderArray<double> Tau_leadChargedCandVtx = {fReader, "Tau_leadChargedCandVtx"};
   TTreeReaderArray<double> Tau_leadChargedCandVty = {fReader, "Tau_leadChargedCandVty"};
   TTreeReaderArray<double> Tau_leadChargedCandVtz = {fReader, "Tau_leadChargedCandVtz"};
   TTreeReaderArray<double> Tau_leadChargedCandTrack_PCAx_bs = {fReader, "Tau_leadChargedCandTrack_PCAx_bs"};
   TTreeReaderArray<double> Tau_leadChargedCandTrack_PCAy_bs = {fReader, "Tau_leadChargedCandTrack_PCAy_bs"};
   TTreeReaderArray<double> Tau_leadChargedCandTrack_PCAz_bs = {fReader, "Tau_leadChargedCandTrack_PCAz_bs"};
   TTreeReaderArray<double> Tau_leadChargedCandTrack_PCAx_pv = {fReader, "Tau_leadChargedCandTrack_PCAx_pv"};
   TTreeReaderArray<double> Tau_leadChargedCandTrack_PCAy_pv = {fReader, "Tau_leadChargedCandTrack_PCAy_pv"};
   TTreeReaderArray<double> Tau_leadChargedCandTrack_PCAz_pv = {fReader, "Tau_leadChargedCandTrack_PCAz_pv"};
   TTreeReaderArray<double> Tau_leadChargedCandTrackFitErrorMatrix_00 = {fReader, "Tau_leadChargedCandTrackFitErrorMatrix_00"};
   TTreeReaderArray<double> Tau_leadChargedCandTrackFitErrorMatrix_01 = {fReader, "Tau_leadChargedCandTrackFitErrorMatrix_01"};
   TTreeReaderArray<double> Tau_leadChargedCandTrackFitErrorMatrix_02 = {fReader, "Tau_leadChargedCandTrackFitErrorMatrix_02"};
   TTreeReaderArray<double> Tau_leadChargedCandTrackFitErrorMatrix_11 = {fReader, "Tau_leadChargedCandTrackFitErrorMatrix_11"};
   TTreeReaderArray<double> Tau_leadChargedCandTrackFitErrorMatrix_12 = {fReader, "Tau_leadChargedCandTrackFitErrorMatrix_12"};
   TTreeReaderArray<double> Tau_leadChargedCandTrackFitErrorMatrix_22 = {fReader, "Tau_leadChargedCandTrackFitErrorMatrix_22"};
   TTreeReaderArray<int> TopTagger_type = {fReader, "TopTagger_type"};
   TTreeReaderArray<float> TopTagger_discriminator = {fReader, "TopTagger_discriminator"};
   TTreeReaderArray<int> TopTagger_jet1Idx = {fReader, "TopTagger_jet1Idx"};
   TTreeReaderArray<int> TopTagger_jet2Idx = {fReader, "TopTagger_jet2Idx"};
   TTreeReaderArray<int> TopTagger_jet3Idx = {fReader, "TopTagger_jet3Idx"};
   TTreeReaderArray<double> Jet_pt = {fReader, "Jet_pt"};
   TTreeReaderArray<double> Jet_eta = {fReader, "Jet_eta"};
   TTreeReaderArray<double> Jet_phi = {fReader, "Jet_phi"};
   TTreeReaderArray<double> Jet_energy = {fReader, "Jet_energy"};
   TTreeReaderArray<double> Jet_mass = {fReader, "Jet_mass"};
   TTreeReaderArray<double> Jet_px = {fReader, "Jet_px"};
   TTreeReaderArray<double> Jet_py = {fReader, "Jet_py"};
   TTreeReaderArray<double> Jet_pz = {fReader, "Jet_pz"};
   TTreeReaderArray<double> Jet_Uncorr_pt = {fReader, "Jet_Uncorr_pt"};
   TTreeReaderArray<double> Jet_L1corr_pt = {fReader, "Jet_L1corr_pt"};
   TTreeReaderArray<double> Jet_pfCombinedInclusiveSecondaryVertexV2BJetTags = {fReader, "Jet_pfCombinedInclusiveSecondaryVertexV2BJetTags"};
   TTreeReaderArray<double> Jet_pfCombinedMVAV2BJetTags = {fReader, "Jet_pfCombinedMVAV2BJetTags"};
   TTreeReaderArray<double> Jet_pfJetProbabilityBJetTags = {fReader, "Jet_pfJetProbabilityBJetTags"};
   TTreeReaderArray<double> Jet_pfCombinedCvsLJetTags = {fReader, "Jet_pfCombinedCvsLJetTags"};
   TTreeReaderArray<double> Jet_pfCombinedCvsBJetTags = {fReader, "Jet_pfCombinedCvsBJetTags"};
   TTreeReaderArray<double> Jet_pfDeepCSVBJetTags = {fReader, "Jet_pfDeepCSVBJetTags"};
   TTreeReaderArray<double> Jet_pfDeepCSVProbb = {fReader, "Jet_pfDeepCSVProbb"};
   TTreeReaderArray<double> Jet_pfDeepCSVProbbb = {fReader, "Jet_pfDeepCSVProbbb"};
   TTreeReaderArray<double> Jet_pfDeepCSVProbc = {fReader, "Jet_pfDeepCSVProbc"};
   TTreeReaderArray<double> Jet_pfDeepCSVProbcc = {fReader, "Jet_pfDeepCSVProbcc"};
   TTreeReaderArray<double> Jet_pfDeepCSVProbudsg = {fReader, "Jet_pfDeepCSVProbudsg"};
   TTreeReaderArray<double> Jet_pfDeepFlavourBJetTags = {fReader, "Jet_pfDeepFlavourBJetTags"};
   TTreeReaderArray<double> Jet_pfDeepFlavourProbb = {fReader, "Jet_pfDeepFlavourProbb"};
   TTreeReaderArray<double> Jet_pfDeepFlavourProbbb = {fReader, "Jet_pfDeepFlavourProbbb"};
   TTreeReaderArray<double> Jet_pfDeepFlavourProblepb = {fReader, "Jet_pfDeepFlavourProblepb"};
   TTreeReaderArray<double> Jet_pfDeepFlavourProbc = {fReader, "Jet_pfDeepFlavourProbc"};
   TTreeReaderArray<double> Jet_pfDeepFlavourProbuds = {fReader, "Jet_pfDeepFlavourProbuds"};
   TTreeReaderArray<double> Jet_pfDeepFlavourProbg = {fReader, "Jet_pfDeepFlavourProbg"};
   TTreeReaderArray<double> Jet_pileupId = {fReader, "Jet_pileupId"};
   TTreeReaderArray<double> Jet_isPFJet = {fReader, "Jet_isPFJet"};
   TTreeReaderArray<double> Jet_isCaloJet = {fReader, "Jet_isCaloJet"};
   TTreeReaderArray<double> Jet_qgLikelihood = {fReader, "Jet_qgLikelihood"};
   TTreeReaderArray<double> Jet_axis2_fromQGtagger = {fReader, "Jet_axis2_fromQGtagger"};
   TTreeReaderArray<double> Jet_mult_fromQGtagger = {fReader, "Jet_mult_fromQGtagger"};
   TTreeReaderArray<double> Jet_ptD_fromQGtager = {fReader, "Jet_ptD_fromQGtager"};
   TTreeReaderArray<double> Jet_axis1 = {fReader, "Jet_axis1"};
   TTreeReaderArray<double> Jet_axis2 = {fReader, "Jet_axis2"};
   TTreeReaderArray<double> Jet_ptD = {fReader, "Jet_ptD"};
   TTreeReaderArray<double> Jet_mult = {fReader, "Jet_mult"};
   TTreeReaderArray<int> Jet_ele_indices = {fReader, "Jet_ele_indices"};
   TTreeReaderArray<int> Jet_ele_number = {fReader, "Jet_ele_number"};
   TTreeReaderArray<int> Jet_mu_indices = {fReader, "Jet_mu_indices"};
   TTreeReaderArray<int> Jet_mu_number = {fReader, "Jet_mu_number"};
   TTreeReaderArray<int> Jet_tau_indices = {fReader, "Jet_tau_indices"};
   TTreeReaderArray<int> Jet_tau_number = {fReader, "Jet_tau_number"};
   TTreeReaderArray<double> Jet_neutralHadEnergyFraction = {fReader, "Jet_neutralHadEnergyFraction"};
   TTreeReaderArray<double> Jet_neutralEmEnergyFraction = {fReader, "Jet_neutralEmEnergyFraction"};
   TTreeReaderArray<double> Jet_chargedHadronEnergyFraction = {fReader, "Jet_chargedHadronEnergyFraction"};
   TTreeReaderArray<double> Jet_chargedEmEnergyFraction = {fReader, "Jet_chargedEmEnergyFraction"};
   TTreeReaderArray<double> Jet_muonEnergyFraction = {fReader, "Jet_muonEnergyFraction"};
   TTreeReaderArray<double> Jet_electronEnergy = {fReader, "Jet_electronEnergy"};
   TTreeReaderArray<double> Jet_photonEnergy = {fReader, "Jet_photonEnergy"};
   TTreeReaderArray<double> Jet_emEnergyFraction = {fReader, "Jet_emEnergyFraction"};
   TTreeReaderArray<double> Jet_numberOfConstituents = {fReader, "Jet_numberOfConstituents"};
   TTreeReaderArray<double> Jet_chargedMultiplicity = {fReader, "Jet_chargedMultiplicity"};
   TTreeReaderArray<double> Jet_vtxMass = {fReader, "Jet_vtxMass"};
   TTreeReaderArray<double> Jet_vtxNtracks = {fReader, "Jet_vtxNtracks"};
   TTreeReaderArray<double> Jet_vtx3DVal = {fReader, "Jet_vtx3DVal"};
   TTreeReaderArray<double> Jet_vtx3DSig = {fReader, "Jet_vtx3DSig"};
   TTreeReaderArray<double> Jet_JesSF = {fReader, "Jet_JesSF"};
   TTreeReaderArray<double> Jet_JesSFup = {fReader, "Jet_JesSFup"};
   TTreeReaderArray<double> Jet_JesSFdown = {fReader, "Jet_JesSFdown"};
   TTreeReaderArray<double> Jet_JerSF = {fReader, "Jet_JerSF"};
   TTreeReaderArray<double> Jet_JerSFup = {fReader, "Jet_JerSFup"};
   TTreeReaderArray<double> Jet_JerSFdown = {fReader, "Jet_JerSFdown"};
   TTreeReaderArray<double> Jet_JesSF_AbsoluteStat_up = {fReader, "Jet_JesSF_AbsoluteStat_up"};
   TTreeReaderArray<double> Jet_JesSF_AbsoluteStat_down = {fReader, "Jet_JesSF_AbsoluteStat_down"};
   TTreeReaderArray<double> Jet_JesSF_AbsoluteScale_up = {fReader, "Jet_JesSF_AbsoluteScale_up"};
   TTreeReaderArray<double> Jet_JesSF_AbsoluteScale_down = {fReader, "Jet_JesSF_AbsoluteScale_down"};
   TTreeReaderArray<double> Jet_JesSF_AbsoluteFlavMap_up = {fReader, "Jet_JesSF_AbsoluteFlavMap_up"};
   TTreeReaderArray<double> Jet_JesSF_AbsoluteFlavMap_down = {fReader, "Jet_JesSF_AbsoluteFlavMap_down"};
   TTreeReaderArray<double> Jet_JesSF_AbsoluteMPFBias_up = {fReader, "Jet_JesSF_AbsoluteMPFBias_up"};
   TTreeReaderArray<double> Jet_JesSF_AbsoluteMPFBias_down = {fReader, "Jet_JesSF_AbsoluteMPFBias_down"};
   TTreeReaderArray<double> Jet_JesSF_Fragmentation_up = {fReader, "Jet_JesSF_Fragmentation_up"};
   TTreeReaderArray<double> Jet_JesSF_Fragmentation_down = {fReader, "Jet_JesSF_Fragmentation_down"};
   TTreeReaderArray<double> Jet_JesSF_SinglePionECAL_up = {fReader, "Jet_JesSF_SinglePionECAL_up"};
   TTreeReaderArray<double> Jet_JesSF_SinglePionECAL_down = {fReader, "Jet_JesSF_SinglePionECAL_down"};
   TTreeReaderArray<double> Jet_JesSF_SinglePionHCAL_up = {fReader, "Jet_JesSF_SinglePionHCAL_up"};
   TTreeReaderArray<double> Jet_JesSF_SinglePionHCAL_down = {fReader, "Jet_JesSF_SinglePionHCAL_down"};
   TTreeReaderArray<double> Jet_JesSF_FlavorQCD_up = {fReader, "Jet_JesSF_FlavorQCD_up"};
   TTreeReaderArray<double> Jet_JesSF_FlavorQCD_down = {fReader, "Jet_JesSF_FlavorQCD_down"};
   TTreeReaderArray<double> Jet_JesSF_TimePtEta_up = {fReader, "Jet_JesSF_TimePtEta_up"};
   TTreeReaderArray<double> Jet_JesSF_TimePtEta_down = {fReader, "Jet_JesSF_TimePtEta_down"};
   TTreeReaderArray<double> Jet_JesSF_RelativeJEREC1_up = {fReader, "Jet_JesSF_RelativeJEREC1_up"};
   TTreeReaderArray<double> Jet_JesSF_RelativeJEREC1_down = {fReader, "Jet_JesSF_RelativeJEREC1_down"};
   TTreeReaderArray<double> Jet_JesSF_RelativeJEREC2_up = {fReader, "Jet_JesSF_RelativeJEREC2_up"};
   TTreeReaderArray<double> Jet_JesSF_RelativeJEREC2_down = {fReader, "Jet_JesSF_RelativeJEREC2_down"};
   TTreeReaderArray<double> Jet_JesSF_RelativeJERHF_up = {fReader, "Jet_JesSF_RelativeJERHF_up"};
   TTreeReaderArray<double> Jet_JesSF_RelativeJERHF_down = {fReader, "Jet_JesSF_RelativeJERHF_down"};
   TTreeReaderArray<double> Jet_JesSF_RelativePtBB_up = {fReader, "Jet_JesSF_RelativePtBB_up"};
   TTreeReaderArray<double> Jet_JesSF_RelativePtBB_down = {fReader, "Jet_JesSF_RelativePtBB_down"};
   TTreeReaderArray<double> Jet_JesSF_RelativePtEC1_up = {fReader, "Jet_JesSF_RelativePtEC1_up"};
   TTreeReaderArray<double> Jet_JesSF_RelativePtEC1_down = {fReader, "Jet_JesSF_RelativePtEC1_down"};
   TTreeReaderArray<double> Jet_JesSF_RelativePtEC2_up = {fReader, "Jet_JesSF_RelativePtEC2_up"};
   TTreeReaderArray<double> Jet_JesSF_RelativePtEC2_down = {fReader, "Jet_JesSF_RelativePtEC2_down"};
   TTreeReaderArray<double> Jet_JesSF_RelativePtHF_up = {fReader, "Jet_JesSF_RelativePtHF_up"};
   TTreeReaderArray<double> Jet_JesSF_RelativePtHF_down = {fReader, "Jet_JesSF_RelativePtHF_down"};
   TTreeReaderArray<double> Jet_JesSF_RelativeBal_up = {fReader, "Jet_JesSF_RelativeBal_up"};
   TTreeReaderArray<double> Jet_JesSF_RelativeBal_down = {fReader, "Jet_JesSF_RelativeBal_down"};
   TTreeReaderArray<double> Jet_JesSF_RelativeFSR_up = {fReader, "Jet_JesSF_RelativeFSR_up"};
   TTreeReaderArray<double> Jet_JesSF_RelativeFSR_down = {fReader, "Jet_JesSF_RelativeFSR_down"};
   TTreeReaderArray<double> Jet_JesSF_RelativeStatFSR_up = {fReader, "Jet_JesSF_RelativeStatFSR_up"};
   TTreeReaderArray<double> Jet_JesSF_RelativeStatFSR_down = {fReader, "Jet_JesSF_RelativeStatFSR_down"};
   TTreeReaderArray<double> Jet_JesSF_RelativeStatEC_up = {fReader, "Jet_JesSF_RelativeStatEC_up"};
   TTreeReaderArray<double> Jet_JesSF_RelativeStatEC_down = {fReader, "Jet_JesSF_RelativeStatEC_down"};
   TTreeReaderArray<double> Jet_JesSF_RelativeStatHF_up = {fReader, "Jet_JesSF_RelativeStatHF_up"};
   TTreeReaderArray<double> Jet_JesSF_RelativeStatHF_down = {fReader, "Jet_JesSF_RelativeStatHF_down"};
   TTreeReaderArray<double> Jet_JesSF_PileUpDataMC_up = {fReader, "Jet_JesSF_PileUpDataMC_up"};
   TTreeReaderArray<double> Jet_JesSF_PileUpDataMC_down = {fReader, "Jet_JesSF_PileUpDataMC_down"};
   TTreeReaderArray<double> Jet_JesSF_PileUpPtRef_up = {fReader, "Jet_JesSF_PileUpPtRef_up"};
   TTreeReaderArray<double> Jet_JesSF_PileUpPtRef_down = {fReader, "Jet_JesSF_PileUpPtRef_down"};
   TTreeReaderArray<double> Jet_JesSF_PileUpPtBB_up = {fReader, "Jet_JesSF_PileUpPtBB_up"};
   TTreeReaderArray<double> Jet_JesSF_PileUpPtBB_down = {fReader, "Jet_JesSF_PileUpPtBB_down"};
   TTreeReaderArray<double> Jet_JesSF_PileUpPtEC1_up = {fReader, "Jet_JesSF_PileUpPtEC1_up"};
   TTreeReaderArray<double> Jet_JesSF_PileUpPtEC1_down = {fReader, "Jet_JesSF_PileUpPtEC1_down"};
   TTreeReaderArray<double> Jet_JesSF_PileUpPtEC2_up = {fReader, "Jet_JesSF_PileUpPtEC2_up"};
   TTreeReaderArray<double> Jet_JesSF_PileUpPtEC2_down = {fReader, "Jet_JesSF_PileUpPtEC2_down"};
   TTreeReaderArray<double> Jet_JesSF_PileUpPtHF_up = {fReader, "Jet_JesSF_PileUpPtHF_up"};
   TTreeReaderArray<double> Jet_JesSF_PileUpPtHF_down = {fReader, "Jet_JesSF_PileUpPtHF_down"};
   TTreeReaderArray<double> Jet_JesSF_PileUpMuZero_up = {fReader, "Jet_JesSF_PileUpMuZero_up"};
   TTreeReaderArray<double> Jet_JesSF_PileUpMuZero_down = {fReader, "Jet_JesSF_PileUpMuZero_down"};
   TTreeReaderArray<double> Jet_JesSF_PileUpEnvelope_up = {fReader, "Jet_JesSF_PileUpEnvelope_up"};
   TTreeReaderArray<double> Jet_JesSF_PileUpEnvelope_down = {fReader, "Jet_JesSF_PileUpEnvelope_down"};
   TTreeReaderArray<double> Jet_JesSF_SubTotalPileUp_up = {fReader, "Jet_JesSF_SubTotalPileUp_up"};
   TTreeReaderArray<double> Jet_JesSF_SubTotalPileUp_down = {fReader, "Jet_JesSF_SubTotalPileUp_down"};
   TTreeReaderArray<double> Jet_JesSF_SubTotalRelative_up = {fReader, "Jet_JesSF_SubTotalRelative_up"};
   TTreeReaderArray<double> Jet_JesSF_SubTotalRelative_down = {fReader, "Jet_JesSF_SubTotalRelative_down"};
   TTreeReaderArray<double> Jet_JesSF_SubTotalPt_up = {fReader, "Jet_JesSF_SubTotalPt_up"};
   TTreeReaderArray<double> Jet_JesSF_SubTotalPt_down = {fReader, "Jet_JesSF_SubTotalPt_down"};
   TTreeReaderArray<double> Jet_JesSF_SubTotalScale_up = {fReader, "Jet_JesSF_SubTotalScale_up"};
   TTreeReaderArray<double> Jet_JesSF_SubTotalScale_down = {fReader, "Jet_JesSF_SubTotalScale_down"};
   TTreeReaderArray<double> Jet_JesSF_SubTotalAbsolute_up = {fReader, "Jet_JesSF_SubTotalAbsolute_up"};
   TTreeReaderArray<double> Jet_JesSF_SubTotalAbsolute_down = {fReader, "Jet_JesSF_SubTotalAbsolute_down"};
   TTreeReaderArray<double> Jet_JesSF_SubTotalMC_up = {fReader, "Jet_JesSF_SubTotalMC_up"};
   TTreeReaderArray<double> Jet_JesSF_SubTotalMC_down = {fReader, "Jet_JesSF_SubTotalMC_down"};
   TTreeReaderArray<double> Jet_JesSF_TotalNoFlavor_up = {fReader, "Jet_JesSF_TotalNoFlavor_up"};
   TTreeReaderArray<double> Jet_JesSF_TotalNoFlavor_down = {fReader, "Jet_JesSF_TotalNoFlavor_down"};
   TTreeReaderArray<double> Jet_JesSF_TotalNoFlavorNoTime_up = {fReader, "Jet_JesSF_TotalNoFlavorNoTime_up"};
   TTreeReaderArray<double> Jet_JesSF_TotalNoFlavorNoTime_down = {fReader, "Jet_JesSF_TotalNoFlavorNoTime_down"};
   TTreeReaderArray<double> Jet_JesSF_FlavorZJet_up = {fReader, "Jet_JesSF_FlavorZJet_up"};
   TTreeReaderArray<double> Jet_JesSF_FlavorZJet_down = {fReader, "Jet_JesSF_FlavorZJet_down"};
   TTreeReaderArray<double> Jet_JesSF_FlavorPhotonJet_up = {fReader, "Jet_JesSF_FlavorPhotonJet_up"};
   TTreeReaderArray<double> Jet_JesSF_FlavorPhotonJet_down = {fReader, "Jet_JesSF_FlavorPhotonJet_down"};
   TTreeReaderArray<double> Jet_JesSF_FlavorPureGluon_up = {fReader, "Jet_JesSF_FlavorPureGluon_up"};
   TTreeReaderArray<double> Jet_JesSF_FlavorPureGluon_down = {fReader, "Jet_JesSF_FlavorPureGluon_down"};
   TTreeReaderArray<double> Jet_JesSF_FlavorPureQuark_up = {fReader, "Jet_JesSF_FlavorPureQuark_up"};
   TTreeReaderArray<double> Jet_JesSF_FlavorPureQuark_down = {fReader, "Jet_JesSF_FlavorPureQuark_down"};
   TTreeReaderArray<double> Jet_JesSF_FlavorPureCharm_up = {fReader, "Jet_JesSF_FlavorPureCharm_up"};
   TTreeReaderArray<double> Jet_JesSF_FlavorPureCharm_down = {fReader, "Jet_JesSF_FlavorPureCharm_down"};
   TTreeReaderArray<double> Jet_JesSF_FlavorPureBottom_up = {fReader, "Jet_JesSF_FlavorPureBottom_up"};
   TTreeReaderArray<double> Jet_JesSF_FlavorPureBottom_down = {fReader, "Jet_JesSF_FlavorPureBottom_down"};
   TTreeReaderValue<Double_t> PUWeight = {fReader, "PUWeight"};
   TTreeReaderValue<Double_t> MinBiasUpWeight = {fReader, "MinBiasUpWeight"};
   TTreeReaderValue<Double_t> MinBiasDownWeight = {fReader, "MinBiasDownWeight"};
   TTreeReaderValue<Double_t> Met_type1PF_pt = {fReader, "Met_type1PF_pt"};
   TTreeReaderValue<Double_t> Met_type1PF_px = {fReader, "Met_type1PF_px"};
   TTreeReaderValue<Double_t> Met_type1PF_py = {fReader, "Met_type1PF_py"};
   TTreeReaderValue<Double_t> Met_type1PF_pz = {fReader, "Met_type1PF_pz"};
   TTreeReaderValue<Double_t> Met_type1PF_phi = {fReader, "Met_type1PF_phi"};
   TTreeReaderValue<Double_t> Met_type1PF_sumEt = {fReader, "Met_type1PF_sumEt"};
   TTreeReaderValue<Double_t> Met_type1PF_shiftedPtUp = {fReader, "Met_type1PF_shiftedPtUp"};
   TTreeReaderValue<Double_t> Met_type1PF_shiftedPtDown = {fReader, "Met_type1PF_shiftedPtDown"};
   TTreeReaderValue<Double_t> Met_type1PF_UnclusteredEnUp = {fReader, "Met_type1PF_UnclusteredEnUp"};
   TTreeReaderValue<Double_t> Met_type1PF_UnclusteredEnDown = {fReader, "Met_type1PF_UnclusteredEnDown"};
   TTreeReaderValue<Double_t> Gen_type1PF_Met = {fReader, "Gen_type1PF_Met"};
   TTreeReaderValue<Double_t> Gen_type1PF_px = {fReader, "Gen_type1PF_px"};
   TTreeReaderValue<Double_t> Gen_type1PF_py = {fReader, "Gen_type1PF_py"};


   objectTSelector(TTree * /*tree*/ =0) { }
   virtual ~objectTSelector() { }
   virtual Int_t   Version() const { return 2; }
   virtual void    Begin(TTree *tree);
   virtual void    SlaveBegin(TTree *tree);
   virtual void    Init(TTree *tree);
   virtual Bool_t  Notify();
   virtual Bool_t  Process(Long64_t entry);
   virtual Int_t   GetEntry(Long64_t entry, Int_t getall = 0) { return fChain ? fChain->GetTree()->GetEntry(entry, getall) : 0; }
   virtual void    SetOption(const char *option) { fOption = option; }
   virtual void    SetObject(TObject *obj) { fObject = obj; }
   virtual void    SetInputList(TList *input) { fInput = input; }
   virtual TList  *GetOutputList() const { return fOutput; }
   virtual void    SlaveTerminate();
   virtual void    Terminate();

   ClassDef(objectTSelector,0);

};

#endif

#ifdef objectTSelector_cxx
void objectTSelector::Init(TTree *tree)
{
   // The Init() function is called when the selector needs to initialize
   // a new tree or chain. Typically here the reader is initialized.
   // It is normally not necessary to make changes to the generated
   // code, but the routine can be extended by the user if needed.
   // Init() will be called many times when running on PROOF
   // (once per file to be processed).

   fReader.SetTree(tree);
}

Bool_t objectTSelector::Notify()
{
   // The Notify() function is called when a new file is opened. This
   // can be either for a new TTree in a TChain or when when a new TTree
   // is started when using PROOF. It is normally not necessary to make changes
   // to the generated code, but the routine can be extended by the
   // user if needed. The return value is currently not used.

   return kTRUE;
}


#endif // #ifdef objectTSelector_cxx
